# Generates Shared/Support/Localizable.xcstrings and Easel/Support/InfoPlist.xcstrings.
# Each entry: key -> (en, ja, ko, zh-Hans, zh-Hant)
import json, os

S = {
"Adjust.Brightness": ("Brightness", "明るさ", "밝기", "亮度", "亮度"),
"Adjust.Contrast": ("Contrast", "コントラスト", "대비", "对比度", "對比度"),
"Adjust.Exposure": ("Exposure", "露出", "노출", "曝光", "曝光"),
"Adjust.Highlights": ("Highlights", "ハイライト", "하이라이트", "高光", "亮部"),
"Adjust.Hue": ("Hue", "色相", "색조", "色相", "色相"),
"Adjust.Reset": ("Reset Adjustments", "調整をリセット", "조절 재설정", "重置调整", "重置調整"),
"Adjust.Saturation": ("Saturation", "彩度", "채도", "饱和度", "飽和度"),
"Adjust.Shadows": ("Shadows", "シャドウ", "그림자", "阴影", "陰影"),
"Adjust.Sharpness": ("Sharpness", "シャープネス", "선명도", "锐度", "銳利度"),
"Adjust.Temperature": ("Warmth", "暖かみ", "따뜻함", "色温", "色溫"),
"Adjust.Tint": ("Tint", "色合い", "색조 보정", "色调", "色調"),
"Adjust.Vibrance": ("Vibrance", "自然な彩度", "생동감", "鲜明度", "鮮豔度"),
"Adjust.Vignette": ("Vignette", "ビネット", "비네트", "暗角", "暈影"),
"Alert.Error.Title": ("Something Went Wrong", "問題が発生しました", "문제가 발생했습니다", "出现问题", "發生問題"),
"BlendMode.Add": ("Add", "加算", "더하기", "相加", "相加"),
"BlendMode.Color": ("Color", "カラー", "색상", "颜色", "顏色"),
"BlendMode.ColorBurn": ("Color Burn", "焼き込みカラー", "색상 번", "颜色加深", "加深顏色"),
"BlendMode.ColorDodge": ("Color Dodge", "覆い焼きカラー", "색상 닷지", "颜色减淡", "加亮顏色"),
"BlendMode.Darken": ("Darken", "比較（暗）", "어둡게", "变暗", "變暗"),
"BlendMode.Difference": ("Difference", "差の絶対値", "차이", "差值", "差異化"),
"BlendMode.Exclusion": ("Exclusion", "除外", "제외", "排除", "排除"),
"BlendMode.HardLight": ("Hard Light", "ハードライト", "하드 라이트", "强光", "實光"),
"BlendMode.Hue": ("Hue", "色相", "색조", "色相", "色相"),
"BlendMode.Lighten": ("Lighten", "比較（明）", "밝게", "变亮", "變亮"),
"BlendMode.LinearBurn": ("Linear Burn", "焼き込み（リニア）", "선형 번", "线性加深", "線性加深"),
"BlendMode.Luminosity": ("Luminosity", "輝度", "광도", "明度", "明度"),
"BlendMode.Multiply": ("Multiply", "乗算", "곱하기", "正片叠底", "色彩增值"),
"BlendMode.Normal": ("Normal", "通常", "표준", "正常", "正常"),
"BlendMode.Overlay": ("Overlay", "オーバーレイ", "오버레이", "叠加", "覆蓋"),
"BlendMode.Saturation": ("Saturation", "彩度", "채도", "饱和度", "飽和度"),
"BlendMode.Screen": ("Screen", "スクリーン", "스크린", "滤色", "濾色"),
"BlendMode.SoftLight": ("Soft Light", "ソフトライト", "소프트 라이트", "柔光", "柔光"),
"Canvas.ActualSize": ("Actual Pixels", "実際のピクセル", "실제 픽셀", "实际像素", "實際像素"),
"Canvas.FitToScreen": ("Fit to Screen", "画面に合わせる", "화면에 맞추기", "适合屏幕", "符合螢幕"),
"Canvas.FlipHorizontal": ("Flip Horizontally", "左右に反転", "수평으로 뒤집기", "水平翻转", "水平翻轉"),
"Canvas.FlipVertical": ("Flip Vertically", "上下に反転", "수직으로 뒤집기", "垂直翻转", "垂直翻轉"),
"Canvas.ImageSize": ("Canvas Size…", "カンバスサイズ…", "캔버스 크기…", "画布大小…", "畫布大小⋯"),
"Canvas.RotateLeft": ("Rotate Left", "左に回転", "왼쪽으로 회전", "向左旋转", "向左旋轉"),
"Canvas.RotateRight": ("Rotate Right", "右に回転", "오른쪽으로 회전", "向右旋转", "向右旋轉"),
"CanvasSize.Picture": ("Picture", "画像", "사진", "图片", "圖片"),
"CanvasSize.Mode.Anchor": ("Keep Size", "サイズを維持", "크기 유지", "保持大小", "維持大小"),
"CanvasSize.Mode.Anchor.Footer": ("The picture stays the same size. The canvas grows around it or crops it, keeping the picture at the anchor.", "画像のサイズは変わりません。カンバスが画像の周りに広がるか切り取られ、画像は基準点の位置に置かれます。", "사진 크기는 그대로 유지됩니다. 캔버스가 사진 주변으로 넓어지거나 잘리며, 사진은 기준점에 놓입니다.", "图片大小保持不变。画布会在图片周围扩展或裁剪，图片保持在锚点位置。", "圖片大小維持不變。畫布會在圖片周圍擴展或裁切，圖片維持在錨點位置。"),
"CanvasSize.Mode.Proportional": ("Scale Proportionally", "縦横比を保って拡大・縮小", "비율에 맞춰 크기 조절", "等比缩放", "等比例縮放"),
"CanvasSize.Mode.Proportional.Footer": ("The picture scales evenly to fit inside the new canvas without distortion. Any room left over is placed using the anchor.", "画像は歪まないように縦横比を保ったまま、新しいカンバスに収まるよう拡大・縮小されます。余った部分は基準点に合わせて配置されます。", "사진이 왜곡 없이 새로운 캔버스 안에 맞도록 비율에 맞춰 크기가 조절됩니다. 남는 공간은 기준점에 따라 배치됩니다.", "图片会等比缩放以适合新画布而不变形。剩余空间根据锚点排列。", "圖片會等比例縮放以符合新畫布而不變形。剩餘空間會依錨點排列。"),
"CanvasSize.Mode.Stretch": ("Stretch to Fill", "引き伸ばして埋める", "늘려서 채우기", "拉伸以填充", "延展以填滿"),
"CanvasSize.Mode.Stretch.Footer": ("The picture is stretched to fill the new canvas exactly, which can change its proportions.", "画像は新しいカンバスにぴったり合うように引き伸ばされます。縦横比が変わる場合があります。", "사진이 새로운 캔버스를 정확히 채우도록 늘어나며, 비율이 바뀔 수 있습니다.", "图片会被拉伸以完全填满新画布，这可能会改变其比例。", "圖片會被延展以完全填滿新畫布，這可能會改變其比例。"),
"Common.Cancel": ("Cancel", "キャンセル", "취소", "取消", "取消"),
"Common.OK": ("OK", "OK", "확인", "好", "好"),
"Crop.Aspect.FourThree": ("4:3", "4:3", "4:3", "4:3", "4:3"),
"Crop.Aspect.Free": ("Freeform", "自由形式", "자유 형식", "自由格式", "自由形式"),
"Crop.Aspect.Original": ("Original", "オリジナル", "원본", "原始", "原始"),
"Crop.Aspect.SixteenNine": ("16:9", "16:9", "16:9", "16:9", "16:9"),
"Crop.Aspect.Square": ("Square", "正方形", "정사각형", "正方形", "正方形"),
"Crop.Aspect.ThreeTwo": ("3:2", "3:2", "3:2", "3:2", "3:2"),
"Error.DocumentDamaged": ("This image could not be opened because part of it is missing or damaged.", "この画像は、一部が見つからないか破損しているため開けませんでした。", "이미지의 일부가 없거나 손상되어 열 수 없습니다.", "无法打开此图像，因为其中部分内容缺失或已损坏。", "無法打開此影像，因為其中部分內容遺失或已損毀。"),
"Error.DocumentTooNew": ("This image was saved by a newer version of Easel. Update Easel to open it.", "この画像は新しいバージョンのEaselで保存されています。開くにはEaselをアップデートしてください。", "이 이미지는 최신 버전의 Easel에서 저장되었습니다. 열려면 Easel을 업데이트하십시오.", "此图像由更新版本的 Easel 存储。请更新 Easel 以打开它。", "此影像由較新版本的 Easel 儲存。請更新 Easel 以打開它。"),
"Error.ImageUnreadable": ("The picture could not be read.", "画像を読み込めませんでした。", "사진을 읽을 수 없습니다.", "无法读取图片。", "無法讀取圖片。"),
"Error.ImageUnwritable": ("The picture could not be saved.", "画像を保存できませんでした。", "사진을 저장할 수 없습니다.", "无法存储图片。", "無法儲存圖片。"),
"Error.ImportFailed": ("Some pictures could not be added.", "一部の画像を追加できませんでした。", "일부 사진을 추가할 수 없습니다.", "部分图片无法添加。", "部分圖片無法加入。"),
"Error.LayerHidden": ("The layer is hidden. Show it to paint on it.", "レイヤーが非表示です。ペイントするには表示してください。", "레이어가 가려져 있습니다. 칠하려면 레이어를 표시하십시오.", "图层已隐藏。请显示图层以在其上绘画。", "圖層已隱藏。請顯示圖層以在上面繪圖。"),
"Error.LayerLocked": ("The layer is locked. Unlock it in Layers to change it.", "レイヤーがロックされています。変更するには「レイヤー」でロックを解除してください。", "레이어가 잠겨 있습니다. 변경하려면 레이어에서 잠금을 해제하십시오.", "图层已锁定。请在“图层”中解锁以进行更改。", "圖層已鎖定。請在「圖層」中解鎖以進行更改。"),
"Error.NoLayer": ("Choose a layer first.", "先にレイヤーを選択してください。", "먼저 레이어를 선택하십시오.", "请先选择一个图层。", "請先選擇一個圖層。"),
"Error.NothingToPaste": ("There is no picture on the clipboard.", "クリップボードに画像がありません。", "클립보드에 사진이 없습니다.", "剪贴板上没有图片。", "剪貼板上沒有圖片。"),
"Error.PhotoUnavailable": ("The photo could not be opened. It may have been deleted or may still be downloading.", "写真を開けませんでした。削除されたか、まだダウンロード中の可能性があります。", "사진을 열 수 없습니다. 삭제되었거나 아직 다운로드 중일 수 있습니다.", "无法打开照片。它可能已被删除或仍在下载。", "無法打開照片。它可能已被刪除或仍在下載。"),
"Error.PhotosAccessDenied": ("Easel needs access to your photo library. You can allow it in Settings.", "Easelには写真ライブラリへのアクセスが必要です。「設定」で許可できます。", "Easel이 사진 보관함에 접근해야 합니다. 설정에서 허용할 수 있습니다.", "Easel 需要访问你的照片图库。你可以在“设置”中允许访问。", "Easel 需要取用你的照片圖庫。你可以在「設定」中允許取用。"),
"Export.DefaultName": ("Image", "画像", "이미지", "图像", "影像"),
"Export.Easel": ("Easel Image (Layers)", "Easel画像（レイヤー付き）", "Easel 이미지(레이어 포함)", "Easel 图像（含图层）", "Easel 影像（含圖層）"),
"Export.HEIC": ("HEIC", "HEIC", "HEIC", "HEIC", "HEIC"),
"Export.JPEG": ("JPEG", "JPEG", "JPEG", "JPEG", "JPEG"),
"Export.PSD": ("Photoshop (Layers)", "Photoshop（レイヤー付き）", "Photoshop(레이어 포함)", "Photoshop（含图层）", "Photoshop（含圖層）"),
"Export.PNG": ("PNG", "PNG", "PNG", "PNG", "PNG"),
"Export.SaveToPhotos": ("Save to Photos", "写真に保存", "사진에 저장", "存储到照片", "儲存到照片"),
"Export.ShareAs": ("Share As", "共有する形式", "공유 형식", "共享格式", "分享格式"),
"Filter.Bloom": ("Bloom", "ブルーム", "블룸", "柔光晕", "光暈"),
"Filter.Chrome": ("Chrome", "クローム", "크롬", "铬黄", "鉻黃"),
"Filter.Comic": ("Comic", "コミック", "만화", "漫画", "漫畫"),
"Filter.Crystallize": ("Crystallize", "結晶化", "결정화", "晶格化", "結晶化"),
"Filter.Fade": ("Fade", "フェード", "바랜 효과", "褪色", "褪色"),
"Filter.Instant": ("Instant", "インスタント", "인스턴트", "拍立得", "即可拍"),
"Filter.Invert": ("Invert", "階調の反転", "반전", "反相", "負片"),
"Filter.Mono": ("Mono", "モノ", "모노", "单色", "單色"),
"Filter.Noir": ("Noir", "ノワール", "누아르", "黑白", "黑白"),
"Filter.Noise": ("Grain", "粒子", "그레인", "颗粒", "顆粒"),
"Filter.None": ("Original", "オリジナル", "원본", "原片", "原始"),
"Filter.Posterize": ("Posterize", "ポスタリゼーション", "포스터화", "色调分离", "色調分離"),
"Filter.Process": ("Process", "プロセス", "프로세스", "冲印", "沖印"),
"Filter.Sepia": ("Sepia", "セピア", "세피아", "棕褐色", "懷舊"),
"Filter.Sharpen": ("Sharpen", "シャープ", "선명하게", "锐化", "銳利化"),
"Filter.Tonal": ("Tonal", "トーン", "색조 흑백", "色调", "色調"),
"Filter.Transfer": ("Transfer", "トランスファー", "트랜스퍼", "岁月", "歲月"),
"Filters.Intensity": ("Intensity", "強さ", "강도", "强度", "強度"),
"Filters.Section.Color": ("Color", "カラー", "색상", "颜色", "顏色"),
"Filters.Section.Effects": ("Effects", "エフェクト", "효과", "效果", "效果"),
"Filters.Section.Looks": ("Looks", "ルック", "룩", "风格", "風格"),
"ImageSize.Anchor": ("Anchor", "基準点", "기준점", "锚点", "錨點"),
"ImageSize.Height": ("Height", "高さ", "높이", "高度", "高度"),
"ImageSize.KeepProportions": ("Keep Proportions", "縦横比を固定", "비율 유지", "保持比例", "維持比例"),
"ImageSize.Original %lld %lld": ("Currently %1$lld × %2$lld pixels", "現在 %1$lld × %2$lld ピクセル", "현재 %1$lld × %2$lld 픽셀", "当前为 %1$lld × %2$lld 像素", "目前為 %1$lld × %2$lld 像素"),
"ImageSize.Pixels": ("px", "px", "px", "像素", "像素"),
"ImageSize.Width": ("Width", "幅", "너비", "宽度", "寬度"),
"LayerFilter.BlackAndWhite": ("Black & White", "白黒", "흑백", "黑白", "黑白"),
"LayerFilter.Brightness": ("Brightness", "明るさ", "밝기", "亮度", "亮度"),
"LayerFilter.Contrast": ("Contrast", "コントラスト", "대비", "对比度", "對比度"),
"LayerFilter.GaussianBlur": ("Gaussian Blur", "ぼかし（ガウス）", "가우시안 흐림", "高斯模糊", "高斯模糊"),
"LayerFilter.Levels": ("Levels", "レベル補正", "레벨", "色阶", "色階"),
"LayerFilter.Curves": ("Curves", "トーンカーブ", "곡선", "曲线", "曲線"),
"LayerFilter.ColorBalance": ("Color Balance", "カラーバランス", "색상 균형", "色彩平衡", "色彩平衡"),
"LayerFilter.GradientMap": ("Gradient Map", "グラデーションマップ", "그레이디언트 맵", "渐变映射", "漸層對應"),
"LayerFilter.LensBlur": ("Lens Blur", "ぼかし（レンズ）", "렌즈 흐림", "镜头模糊", "鏡頭模糊"),
"LayerFilter.NoiseReduction": ("Reduce Noise", "ノイズ軽減", "노이즈 감소", "减少杂色", "減少雜訊"),
"LayerFilters.CyanRed": ("Cyan – Red", "シアン – レッド", "시안 – 빨강", "青色 – 红色", "青色 – 紅色"),
"LayerFilters.MagentaGreen": ("Magenta – Green", "マゼンタ – グリーン", "마젠타 – 초록", "洋红 – 绿色", "洋紅 – 綠色"),
"LayerFilters.YellowBlue": ("Yellow – Blue", "イエロー – ブルー", "노랑 – 파랑", "黄色 – 蓝色", "黃色 – 藍色"),
"LayerFilters.Shadows": ("Shadows", "シャドウ", "그림자", "阴影", "陰影"),
"LayerFilters.Highlights": ("Highlights", "ハイライト", "하이라이트", "高光", "亮部"),
"LayerFilters.Black": ("Black Point", "ブラックポイント", "검정 포인트", "黑场", "黑點"),
"LayerFilters.White": ("White Point", "ホワイトポイント", "흰색 포인트", "白场", "白點"),
"LayerFilters.Gamma": ("Midtones", "中間調", "중간 톤", "中间调", "中間調"),
"LayerFilter.Mosaic": ("Mosaic", "モザイク", "모자이크", "马赛克", "馬賽克"),
"LayerFilter.MotionBlur": ("Motion Blur", "ぼかし（移動）", "동작 흐림", "动感模糊", "動態模糊"),
"LayerFilter.Saturation": ("Saturation", "彩度", "채도", "饱和度", "飽和度"),
"LayerFilter.Sepia": ("Sepia", "セピア", "세피아", "棕褐色", "懷舊"),
"LayerFilter.ZoomBlur": ("Zoom Blur", "ぼかし（ズーム）", "확대/축소 흐림", "缩放模糊", "縮放模糊"),
"LayerFilters.Add": ("Add Filter", "フィルタを追加", "필터 추가", "添加滤镜", "加入濾鏡"),
"LayerFilters.Amount": ("Amount", "量", "양", "数量", "數量"),
"LayerFilters.Angle": ("Angle", "角度", "각도", "角度", "角度"),
"LayerFilters.ApplyAll": ("Apply Filters to Layer", "フィルタをレイヤーに適用", "레이어에 필터 적용", "将滤镜应用到图层", "將濾鏡套用至圖層"),
"LayerFilters.CenterX": ("Center (Horizontal)", "中心（水平）", "중심(수평)", "中心（水平）", "中心（水平）"),
"LayerFilters.CenterY": ("Center (Vertical)", "中心（垂直）", "중심(수직)", "中心（垂直）", "中心（垂直）"),
"LayerFilters.Empty": ("No Filters", "フィルタなし", "필터 없음", "没有滤镜", "沒有濾鏡"),
"LayerFilters.Empty.Detail": ("Filters change how this layer looks without changing its pixels, so they can be adjusted or removed at any time.", "フィルタはピクセルを変更せずにレイヤーの見た目を変えるので、いつでも調整したり取り除いたりできます。", "필터는 픽셀을 변경하지 않고 레이어의 모양을 바꾸므로 언제든지 조절하거나 제거할 수 있습니다.", "滤镜会更改此图层的外观而不更改其像素，因此可以随时调整或移除。", "濾鏡會更改此圖層的外觀而不更改其像素，因此可以隨時調整或移除。"),
"LayerFilters.Hide": ("Turn Off Filter", "フィルタをオフにする", "필터 끄기", "关闭滤镜", "關閉濾鏡"),
"LayerFilters.Show": ("Turn On Filter", "フィルタをオンにする", "필터 켜기", "打开滤镜", "開啟濾鏡"),
"LayerFilters.Footer": ("Filters run from top to bottom. Touch and hold a filter to drag it into a new place.", "フィルタは上から順に適用されます。フィルタを長押しすると、ドラッグして並べ替えられます。", "필터는 위에서 아래 순서로 적용됩니다. 필터를 길게 터치하여 드래그하면 순서를 변경할 수 있습니다.", "滤镜从上到下依次应用。按住滤镜即可拖移以重新排序。", "濾鏡由上至下依序套用。按住濾鏡即可拖移以重新排序。"),
"LayerFilters.Remove": ("Remove Filter", "フィルタを削除", "필터 제거", "移除滤镜", "移除濾鏡"),
"LayerFilters.RemoveAll": ("Remove All Filters", "すべてのフィルタを削除", "모든 필터 제거", "移除所有滤镜", "移除所有濾鏡"),
"Panel.Looks.Title": ("Looks", "ルック", "룩", "风格", "風格"),
"Mask.Title": ("Mask", "マスク", "마스크", "蒙版", "遮色片"),
"Mask.Add": ("Add Mask", "マスクを追加", "마스크 추가", "添加蒙版", "加入遮色片"),
"Mask.AddFromSelection": ("Add Mask from Selection", "選択範囲からマスクを追加", "선택 영역에서 마스크 추가", "从选区添加蒙版", "從選取範圍加入遮色片"),
"Mask.Edit": ("Paint on Mask", "マスクにペイント", "마스크에 칠하기", "在蒙版上绘画", "在遮色片上繪圖"),
"Mask.Enabled": ("Use Mask", "マスクを使用", "마스크 사용", "使用蒙版", "使用遮色片"),
"Mask.Actions": ("Mask Actions", "マスクの操作", "마스크 동작", "蒙版操作", "遮色片動作"),
"Mask.HideSelection": ("Hide Selection", "選択範囲を隠す", "선택 영역 가리기", "隐藏选区", "隱藏選取範圍"),
"Mask.RevealSelection": ("Reveal Selection", "選択範囲を表示", "선택 영역 표시", "显示选区", "顯示選取範圍"),
"Mask.Invert": ("Invert Mask", "マスクを反転", "마스크 반전", "反转蒙版", "反轉遮色片"),
"Mask.Apply": ("Apply Mask to Layer", "マスクをレイヤーに適用", "레이어에 마스크 적용", "将蒙版应用到图层", "將遮色片套用至圖層"),
"Mask.Delete": ("Delete Mask", "マスクを削除", "마스크 삭제", "删除蒙版", "刪除遮色片"),
"Mask.Footer": ("While painting on the mask, the brush hides the layer and the eraser reveals it again.", "マスクにペイントしている間は、ブラシでレイヤーを隠し、消しゴムで再び表示できます。", "마스크에 칠하는 동안 브러시는 레이어를 가리고 지우개는 다시 표시합니다.", "在蒙版上绘画时，画笔会隐藏图层，橡皮擦会重新显示图层。", "在遮色片上繪圖時，筆刷會隱藏圖層，橡皮擦會重新顯示圖層。"),
"Mask.Editing": ("Painting on Mask", "マスクにペイント中", "마스크에 칠하는 중", "正在蒙版上绘画", "正在遮色片上繪圖"),
"Error.MaskTool": ("Only the brush, eraser and gradient can paint on a mask.", "マスクにペイントできるのは、ブラシ、消しゴム、グラデーションだけです。", "마스크에는 브러시, 지우개, 그라디언트만 칠할 수 있습니다.", "只有画笔、橡皮擦和渐变可以在蒙版上绘画。", "只有筆刷、橡皮擦和漸層可以在遮色片上繪圖。"),
"Error.NoObjectFound": ("No people, animals or objects were found in the picture.", "画像内に人物、動物、物体が見つかりませんでした。", "사진에서 사람, 동물 또는 사물을 찾을 수 없습니다.", "未在图片中找到人物、动物或物体。", "未在圖片中找到人物、動物或物體。"),
"Error.NoObjectHere": ("There is no object there. Tap a person, animal or thing to select it.", "そこにはオブジェクトがありません。人物、動物、物体をタップして選択してください。", "그곳에는 개체가 없습니다. 사람, 동물 또는 사물을 탭하여 선택하십시오.", "那里没有对象。请轻点人物、动物或物体以选择。", "那裡沒有物件。請點一下人物、動物或物體以選取。"),
"Error.ObjectSelectionUnavailable": ("Object selection isn't available on this device.", "このデバイスではオブジェクト選択を使用できません。", "이 기기에서는 개체 선택을 사용할 수 없습니다.", "此设备不支持选择对象。", "此裝置不支援選取物件。"),
"Error.PSDUnsupported": ("This Photoshop document uses a colour mode or size Easel can't open.", "このPhotoshop書類は、Easelで開けないカラーモードまたはサイズを使用しています。", "이 Photoshop 문서는 Easel에서 열 수 없는 색상 모드 또는 크기를 사용합니다.", "此 Photoshop 文稿使用了 Easel 无法打开的颜色模式或尺寸。", "此 Photoshop 文件使用了 Easel 無法打開的色彩模式或尺寸。"),
"Groups.Group": ("Group Layer", "レイヤーをグループ化", "레이어 그룹화", "编组图层", "群組圖層"),
"Groups.Ungroup": ("Ungroup", "グループ解除", "그룹 해제", "取消编组", "取消群組"),
"Groups.Merge": ("Merge Group", "グループを結合", "그룹 병합", "合并组", "合併群組"),
"Groups.Delete": ("Delete Group", "グループを削除", "그룹 삭제", "删除组", "刪除群組"),
"Groups.MoveTo": ("Move to Group", "グループへ移動", "그룹으로 이동", "移到组", "移至群組"),
"Groups.NoGroup": ("No Group", "グループなし", "그룹 없음", "无组", "無群組"),
"Groups.Collapse": ("Collapse Group", "グループを閉じる", "그룹 접기", "折叠组", "收合群組"),
"Groups.Expand": ("Expand Group", "グループを開く", "그룹 펼치기", "展开组", "展開群組"),
"Groups.Section": ("Group", "グループ", "그룹", "组", "群組"),
"Vector.Combine": ("Combine Shapes", "シェイプを結合", "도형 결합", "组合形状", "組合形狀"),
"Vector.Unite": ("Unite", "合体", "합치기", "联集", "聯集"),
"Vector.Subtract": ("Subtract", "前面で型抜き", "빼기", "减去顶层", "減去頂層"),
"Vector.Intersect": ("Intersect", "交差", "교차", "交集", "交集"),
"Vector.Exclude": ("Exclude", "中マド", "제외", "差集", "差集"),
"Launch.EditPhoto": ("Edit a Photo", "写真を編集", "사진 편집", "编辑照片", "編輯照片"),
"Launch.NewImage": ("New Image", "新規画像", "새로운 이미지", "新建图像", "新增影像"),
"Layer.CopyName %@": ("%@ Copy", "%@のコピー", "%@ 사본", "%@ 副本", "%@ 副本"),
"Layer.DefaultName.Background": ("Background", "背景", "배경", "背景", "背景"),
"Layer.DefaultName.Group": ("Group", "グループ", "그룹", "组", "群組"),
"Layer.DefaultName.Image": ("Image", "画像", "이미지", "图像", "影像"),
"Layer.DefaultName.Layer": ("Layer", "レイヤー", "레이어", "图层", "圖層"),
"Layer.DefaultName.Pasted": ("Pasted", "ペースト", "붙여넣음", "粘贴", "貼上"),
"Layer.DefaultName.PixelmatorPreview": ("Pixelmator Preview", "Pixelmatorのプレビュー", "Pixelmator 미리보기", "Pixelmator 预览", "Pixelmator 預覽"),
"Layer.DefaultName.Path": ("Path", "パス", "패스", "路径", "路徑"),
"Layer.DefaultName.Photo": ("Photo", "写真", "사진", "照片", "照片"),
"Layers.Add": ("Add Layer", "レイヤーを追加", "레이어 추가", "添加图层", "加入圖層"),
"Layers.BlendMode": ("Blend Mode", "描画モード", "혼합 모드", "混合模式", "混合模式"),
"Layers.Copy": ("Copy", "コピー", "복사", "拷贝", "拷貝"),
"Layers.Delete": ("Delete Layer", "レイヤーを削除", "레이어 삭제", "删除图层", "刪除圖層"),
"Layers.Duplicate": ("Duplicate", "複製", "복제", "复制", "複製"),
"Layers.Flatten": ("Flatten Image", "画像を統合", "이미지 병합", "拼合图像", "影像平面化"),
"Layers.Hide": ("Hide Layer", "レイヤーを非表示", "레이어 가리기", "隐藏图层", "隱藏圖層"),
"Layers.ImportFiles": ("From Files", "“ファイル”から", "파일에서", "从“文件”", "從「檔案」"),
"Layers.ImportPhotos": ("From Photos", "“写真”から", "사진에서", "从“照片”", "從「照片」"),
"Layers.Lock": ("Lock", "ロック", "잠금", "锁定", "鎖定"),
"Layers.Locked": ("Locked", "ロック中", "잠김", "已锁定", "已鎖定"),
"Layers.MergeDown": ("Merge Down", "下のレイヤーと結合", "아래 레이어와 병합", "向下合并", "向下合併"),
"Layers.More": ("More", "その他", "더 보기", "更多", "更多"),
"Layers.MoveDown": ("Move Down", "下へ移動", "아래로 이동", "下移", "下移"),
"Layers.MoveUp": ("Move Up", "上へ移動", "위로 이동", "上移", "上移"),
"Layers.NewLayer": ("New Layer", "新規レイヤー", "새로운 레이어", "新建图层", "新增圖層"),
"Layers.Opacity": ("Opacity", "不透明度", "불투명도", "不透明度", "不透明度"),
"Layers.Paste": ("Paste", "ペースト", "붙여넣기", "粘贴", "貼上"),
"Layers.Rasterize": ("Rasterize", "ラスタライズ", "래스터화", "栅格化", "點陣化"),
"Layers.Rename": ("Rename", "名称変更", "이름 변경", "重新命名", "重新命名"),
"Layers.Rename.Confirm": ("Rename", "名称変更", "이름 변경", "重新命名", "重新命名"),
"Layers.Rename.Placeholder": ("Layer Name", "レイヤー名", "레이어 이름", "图层名称", "圖層名稱"),
"Layers.Rename.Title": ("Rename Layer", "レイヤー名を変更", "레이어 이름 변경", "重新命名图层", "重新命名圖層"),
"Layers.Section.Appearance": ("Layer", "レイヤー", "레이어", "图层", "圖層"),
"Layers.Vector": ("Vector Layer", "ベクターレイヤー", "벡터 레이어", "矢量图层", "向量圖層"),
"Layers.Show": ("Show Layer", "レイヤーを表示", "레이어 표시", "显示图层", "顯示圖層"),
"Layers.Unlock": ("Unlock", "ロックを解除", "잠금 해제", "解锁", "解鎖"),
"Options.AspectRatio": ("Aspect Ratio", "縦横比", "화면 비율", "长宽比", "長寬比"),
"Options.BrushSettings": ("Brush Settings", "ブラシ設定", "브러시 설정", "画笔设置", "筆刷設定"),
"Options.Color": ("Color", "カラー", "색상", "颜色", "顏色"),
"Options.CropApply": ("Crop", "切り取る", "자르기", "裁剪", "裁切"),
"Options.CropReset": ("Reset Crop", "切り取りをリセット", "자르기 재설정", "重置裁剪", "重置裁切"),
"Options.EditText": ("Edit Text", "テキストを編集", "텍스트 편집", "编辑文本", "編輯文字"),
"Options.FinishPath": ("Finish Path", "パスを完了", "패스 완료", "完成路径", "完成路徑"),
"Options.TapToStartPath": ("Tap for corners, drag for curves", "タップで角、ドラッグで曲線", "탭하여 모서리, 드래그하여 곡선", "轻点添加角点，拖移添加曲线", "點一下加入角點，拖移加入曲線"),
"Options.Fill": ("Fill", "塗り", "채우기", "填充", "填色"),
"Options.Stroke": ("Stroke", "線", "선", "描边", "筆畫"),
"Options.MakeSmooth": ("Make Smooth", "滑らかにする", "부드럽게", "转为平滑", "轉為平滑"),
"Options.MakeCorner": ("Make Corner", "角にする", "모서리로", "转为角点", "轉為角點"),
"Options.AddPoint": ("Add Point After", "後ろにポイントを追加", "뒤에 포인트 추가", "在后面添加锚点", "在後方加入錨點"),
"Options.DeletePoint": ("Delete Point", "ポイントを削除", "포인트 삭제", "删除锚点", "刪除錨點"),
"Options.ClosePath": ("Close Path", "パスを閉じる", "패스 닫기", "闭合路径", "封閉路徑"),
"Options.OpenPath": ("Open Path", "パスを開く", "패스 열기", "断开路径", "斷開路徑"),
"Options.PickVectorLayer": ("Tap a shape or path to edit it", "図形やパスをタップして編集", "도형이나 패스를 탭하여 편집", "轻点形状或路径以编辑", "點一下形狀或路徑以編輯"),
"Options.PenAddsToLayer": ("Add Paths to Current Layer", "現在のレイヤーにパスを追加", "현재 레이어에 패스 추가", "将路径添加到当前图层", "將路徑加入目前圖層"),
"Options.SelectMultiplePoints": ("Select Multiple Points", "複数のポイントを選択", "여러 포인트 선택", "选择多个锚点", "選取多個錨點"),
"Options.SelectAllPoints": ("Select All Points", "すべてのポイントを選択", "모든 포인트 선택", "选择所有锚点", "選取所有錨點"),
"Options.PathText": ("Text on Path", "パス上文字", "패스 위의 텍스트", "路径文字", "路徑文字"),
"Options.PathText.Apply": ("Set Text", "テキストを設定", "텍스트 설정", "设置文本", "設定文字"),
"Options.PathText.Start": ("Starts At", "開始位置", "시작 위치", "起始位置", "起始位置"),
"Options.PathText.Remove": ("Remove Text", "テキストを削除", "텍스트 제거", "移除文本", "移除文字"),
"Options.FitToCanvas": ("Fit to Canvas", "カンバスに合わせる", "캔버스에 맞추기", "适合画布", "符合畫布"),
"Options.FlipHorizontal": ("Flip Layer Horizontally", "レイヤーを左右に反転", "레이어를 수평으로 뒤집기", "水平翻转图层", "水平翻轉圖層"),
"Options.FlipVertical": ("Flip Layer Vertically", "レイヤーを上下に反転", "레이어를 수직으로 뒤집기", "垂直翻转图层", "垂直翻轉圖層"),
"Options.LineWidth": ("Line Width", "線の太さ", "선 두께", "线宽", "線條寬度"),
"Options.Opacity": ("Opacity", "不透明度", "불투명도", "不透明度", "不透明度"),
"Options.PencilPressure": ("Apple Pencil Pressure", "Apple Pencilの筆圧", "Apple Pencil 압력", "Apple Pencil 压力", "Apple Pencil 壓力"),
"Options.ResetTransform": ("Reset Size and Position", "サイズと位置をリセット", "크기 및 위치 재설정", "重置大小和位置", "重置大小與位置"),
"Options.RotateLayer": ("Rotate Layer", "レイヤーを回転", "레이어 회전", "旋转图层", "旋轉圖層"),
"Options.Rotation": ("Rotation", "回転", "회전", "旋转", "旋轉"),
"Options.Scale": ("Scale", "拡大・縮小", "크기", "缩放", "縮放"),
"Options.SelectionActions": ("Selection", "選択範囲", "선택 영역", "选区", "選取範圍"),
"Options.ShapeFilled": ("Fill Shape", "図形を塗りつぶす", "도형 채우기", "填充形状", "填滿形狀"),
"Options.Size": ("Size", "サイズ", "크기", "大小", "大小"),
"Options.Softness": ("Softness", "やわらかさ", "부드러움", "柔和度", "柔和度"),
"Options.TapToAddText": ("Tap to add text", "タップしてテキストを追加", "탭하여 텍스트 추가", "轻点以添加文本", "點一下以加入文字"),
"Options.Tolerance": ("Tolerance", "許容値", "허용치", "容差", "容許度"),
"Options.Transform": ("Size and Rotation", "サイズと回転", "크기 및 회전", "大小与旋转", "大小與旋轉"),
"Panel.Adjustments.Title": ("Adjust", "調整", "조절", "调整", "調整"),
"Panel.Filters.Title": ("Filters", "フィルタ", "필터", "滤镜", "濾鏡"),
"Panel.ImageSize.Title": ("Canvas Size", "カンバスサイズ", "캔버스 크기", "画布大小", "畫布大小"),
"Panel.Layers.Title": ("Layers", "レイヤー", "레이어", "图层", "圖層"),
"Panel.Text.Title": ("Text", "テキスト", "텍스트", "文本", "文字"),
"PhotoEditor.Discard.Confirm": ("Discard Changes", "変更内容を破棄", "변경 사항 폐기", "放弃更改", "放棄更改"),
"PhotoEditor.Discard.Title": ("Discard your changes to this photo?", "この写真への変更内容を破棄しますか?", "이 사진의 변경 사항을 폐기하겠습니까?", "要放弃对此照片的更改吗？", "要放棄對此照片的更改嗎？"),
"PhotoEditor.Revert": ("Revert to Original", "オリジナルに戻す", "원본으로 복귀", "复原到原始状态", "回復成原始狀態"),
"PhotoEditor.Save": ("Save", "保存", "저장", "存储", "儲存"),
"PhotoEditor.Title": ("Edit Photo", "写真を編集", "사진 편집", "编辑照片", "編輯照片"),
"Select.All": ("Select All", "すべてを選択", "모두 선택", "全选", "全選"),
"Select.Clear": ("Delete Selected Area", "選択範囲を削除", "선택 영역 삭제", "删除选区内容", "刪除選取範圍內容"),
"Select.CopyToLayer": ("Copy to New Layer", "新規レイヤーにコピー", "새로운 레이어로 복사", "拷贝到新图层", "拷貝到新圖層"),
"Select.CropToSelection": ("Crop to Selection", "選択範囲で切り取る", "선택 영역으로 자르기", "裁剪到选区", "裁切至選取範圍"),
"Select.CutToLayer": ("Cut to New Layer", "新規レイヤーにカット", "새로운 레이어로 오려두기", "剪切到新图层", "剪下至新圖層"),
"Select.Deselect": ("Deselect", "選択を解除", "선택 해제", "取消选择", "取消選取"),
"Select.Ellipse": ("Ellipse", "楕円形", "타원", "椭圆", "橢圓"),
"Select.Fill": ("Fill Selection", "選択範囲を塗りつぶす", "선택 영역 채우기", "填充选区", "填滿選取範圍"),
"Select.Invert": ("Invert Selection", "選択範囲を反転", "선택 영역 반전", "反选", "反轉選取範圍"),
"Select.Lasso": ("Freehand", "フリーハンド", "자유형", "手绘", "手繪"),
"Select.Magic": ("Magic Select", "自動選択", "자동 선택", "魔棒", "魔術棒"),
"Select.Magnetic": ("Magnetic Lasso", "マグネット選択", "자석 올가미", "磁性套索", "磁性套索"),
"Select.Object": ("Object Select", "オブジェクト選択", "개체 선택", "选择对象", "選取物件"),
"Mask.RemoveBackground": ("Remove Background", "背景を削除", "배경 제거", "移除背景", "移除背景"),
"Select.FillFromSurroundings": ("Fill from Surroundings", "周囲から塗りつぶし", "주변으로 채우기", "根据周围填充", "依周圍填滿"),
"Select.Subject": ("Select Subject", "被写体を選択", "피사체 선택", "选择主体", "選取主體"),
"Select.Rectangle": ("Rectangle", "長方形", "직사각형", "矩形", "矩形"),
"Shape.Arrow": ("Arrow", "矢印", "화살표", "箭头", "箭頭"),
"Shape.Ellipse": ("Ellipse", "楕円形", "타원", "椭圆", "橢圓"),
"Shape.Line": ("Line", "線", "선", "线条", "線條"),
"Shape.Rectangle": ("Rectangle", "長方形", "직사각형", "矩形", "矩形"),
"Text.Outline": ("Outline", "輪郭", "외곽선", "轮廓", "外框"),
"Text.Outline.Show": ("Outline Text", "テキストに輪郭を付ける", "텍스트 외곽선", "为文本添加轮廓", "為文字加上外框"),
"Text.Outline.Width": ("Width", "太さ", "두께", "宽度", "寬度"),
"Text.Background": ("Background", "背景", "배경", "背景", "背景"),
"Text.Background.Show": ("Background Box", "背景ボックス", "배경 상자", "背景框", "背景框"),
"Text.Background.Padding": ("Padding", "余白", "여백", "边距", "邊距"),
"Text.Background.Corners": ("Rounded Corners", "角の丸み", "둥근 모서리", "圆角", "圓角"),
"Text.Alignment": ("Alignment", "揃え", "정렬", "对齐", "對齊"),
"Text.Alignment.Center": ("Center", "中央揃え", "가운데 정렬", "居中", "置中"),
"Text.Alignment.Leading": ("Left", "左揃え", "왼쪽 정렬", "左对齐", "靠左"),
"Text.Alignment.Trailing": ("Right", "右揃え", "오른쪽 정렬", "右对齐", "靠右"),
"Text.Bold": ("Bold", "太字", "볼드체", "粗体", "粗體"),
"Text.Color": ("Color", "カラー", "색상", "颜色", "顏色"),
"Text.Design": ("Font", "フォント", "서체", "字体", "字體"),
"Text.Design.Default": ("System", "システム", "시스템", "系统", "系統"),
"Text.Design.Monospaced": ("Monospaced", "等幅", "고정폭", "等宽", "等寬"),
"Text.Design.Rounded": ("Rounded", "丸ゴシック", "둥근", "圆体", "圓體"),
"Text.Design.Serif": ("Serif", "セリフ", "세리프", "衬线", "襯線"),
"Text.Italic": ("Italic", "斜体", "이탤릭체", "斜体", "斜體"),
"Text.NoTextLayer": ("No Text Layer", "テキストレイヤーがありません", "텍스트 레이어 없음", "没有文本图层", "沒有文字圖層"),
"Text.NoTextLayer.Detail": ("Pick the Text tool and tap the canvas to add text.", "テキストツールを選んでカンバスをタップすると、テキストを追加できます。", "텍스트 도구를 선택하고 캔버스를 탭하여 텍스트를 추가하십시오.", "选择文本工具并轻点画布以添加文本。", "選擇文字工具並點一下畫布以加入文字。"),
"Text.Placeholder": ("Text", "テキスト", "텍스트", "文本", "文字"),
"Text.Size": ("Size", "サイズ", "크기", "大小", "大小"),
"TitleMenu.ConvertToEasel": ("Keep Layers", "レイヤーを保持", "레이어 유지", "保留图层", "保留圖層"),
"TitleMenu.ConvertToEasel.Footer": ("Pictures are flattened when saved. Turn this file into an Easel image to keep its layers.", "画像ファイルは保存時に統合されます。レイヤーを保持するには、このファイルをEasel画像に変換してください。", "사진 파일은 저장할 때 병합됩니다. 레이어를 유지하려면 이 파일을 Easel 이미지로 변환하십시오.", "图片在存储时会被拼合。将此文件转换为 Easel 图像以保留其图层。", "圖片在儲存時會被平面化。將此檔案轉換為 Easel 影像以保留其圖層。"),
"Tool.Blur": ("Blur", "ぼかし", "흐림", "模糊", "模糊"),
"Tool.Liquify": ("Liquify", "ゆがみ", "픽셀 유동화", "液化", "液化"),
"Tool.Heal": ("Heal", "修復", "복구", "修复", "修復"),
"Tool.Clone": ("Clone Stamp", "コピースタンプ", "복제 도장", "仿制图章", "仿製印章"),
"Options.CloneSource": ("Set Source", "コピー元を設定", "소스 설정", "设定源", "設定來源"),
"Tool.Mosaic": ("Mosaic", "モザイク", "모자이크", "马赛克", "馬賽克"),
"Tool.Smudge": ("Smudge", "指先", "손가락", "涂抹", "指尖"),
"Options.Strength": ("Strength", "強さ", "강도", "强度", "強度"),
"Tool.Pen": ("Pen", "ペン", "펜", "钢笔", "鋼筆"),
"Tool.Nodes": ("Edit Points", "ポイントを編集", "포인트 편집", "编辑锚点", "編輯錨點"),
"Options.PencilTilt": ("Apple Pencil Tilt", "Apple Pencilの傾き", "Apple Pencil 기울기", "Apple Pencil 倾斜", "Apple Pencil 傾斜"),
"Brush.Library": ("Brushes", "ブラシ", "브러시", "画笔", "筆刷"),
"Brush.Saved": ("Saved", "保存済み", "저장됨", "已存储", "已儲存"),
"Brush.SaveCurrent": ("Save Brush", "ブラシを保存", "브러시 저장", "存储画笔", "儲存筆刷"),
"Brush.DeleteSaved": ("Delete Saved Brush", "保存したブラシを削除", "저장된 브러시 삭제", "删除存储的画笔", "刪除已儲存的筆刷"),
"Brush.Name": ("Name", "名前", "이름", "名称", "名稱"),
"Brush.Save": ("Save", "保存", "저장", "存储", "儲存"),
"Brush.Preset.Ink": ("Ink Pen", "インクペン", "잉크 펜", "墨水笔", "墨水筆"),
"Brush.Preset.Sketch": ("Sketching Pencil", "スケッチ鉛筆", "스케치 연필", "素描铅笔", "素描鉛筆"),
"Brush.Preset.BrushPen": ("Brush Pen", "筆ペン", "붓펜", "毛笔", "毛筆"),
"Brush.Preset.SoftAirbrush": ("Soft Airbrush", "ソフトエアブラシ", "부드러운 에어브러시", "柔和喷枪", "柔和噴槍"),
"Brush.Preset.Pastel": ("Pastel", "パステル", "파스텔", "粉彩", "粉彩"),
"Canvas.ShowRulers": ("Show Rulers", "定規を表示", "눈금자 보기", "显示标尺", "顯示尺標"),
"Canvas.ClearGuides": ("Clear Guides", "ガイドを消去", "가이드 지우기", "清除参考线", "清除參考線"),
"Swatches.Document": ("In This Picture", "このピクチャ", "이 그림", "此图片", "此圖片"),
"Swatches.System": ("System Colors", "システムカラー", "시스템 색상", "系统颜色", "系統顏色"),
"Swatches.MoreColors": ("More Colors", "その他のカラー", "기타 색상", "更多颜色", "更多顏色"),
"Swatches.Add": ("Add Current Color", "現在のカラーを追加", "현재 색상 추가", "添加当前颜色", "加入目前顏色"),
"Swatches.Remove": ("Remove Swatch", "スウォッチを削除", "견본 제거", "移除色板", "移除色票"),
"Color.Red": ("Red", "レッド", "빨간색", "红色", "紅色"),
"Color.Orange": ("Orange", "オレンジ", "주황색", "橙色", "橙色"),
"Color.Yellow": ("Yellow", "イエロー", "노란색", "黄色", "黃色"),
"Color.Green": ("Green", "グリーン", "초록색", "绿色", "綠色"),
"Color.Mint": ("Mint", "ミント", "민트색", "薄荷色", "薄荷色"),
"Color.Teal": ("Teal", "ティール", "청록색", "蓝绿色", "藍綠色"),
"Color.Cyan": ("Cyan", "シアン", "시안", "青色", "青色"),
"Color.Blue": ("Blue", "ブルー", "파란색", "蓝色", "藍色"),
"Color.Indigo": ("Indigo", "インディゴ", "남색", "靛蓝色", "靛藍色"),
"Color.Purple": ("Purple", "パープル", "보라색", "紫色", "紫色"),
"Color.Pink": ("Pink", "ピンク", "분홍색", "粉红色", "粉紅色"),
"Color.Brown": ("Brown", "ブラウン", "갈색", "棕色", "棕色"),
"Color.Black": ("Black", "ブラック", "검은색", "黑色", "黑色"),
"Color.Grey": ("Gray", "グレイ", "회색", "灰色", "灰色"),
"Color.Grey3": ("Light Gray", "ライトグレイ", "밝은 회색", "浅灰色", "淺灰色"),
"Color.White": ("White", "ホワイト", "흰색", "白色", "白色"),
"Panel.History.Title": ("History", "ヒストリー", "작업 내역", "历史记录", "步驟記錄"),
"History.Opened": ("Opened", "開いた状態", "열었을 때", "打开时", "打開時"),
"History.Footer": ("Tap a step to go back to it. Making a change after going back drops the steps after it.", "ステップをタップするとその時点に戻ります。戻った後に変更すると、それ以降のステップは消えます。", "단계를 탭하면 해당 시점으로 돌아갑니다. 돌아간 후 변경하면 그 이후의 단계는 사라집니다.", "轻点某一步可返回该步骤。返回后再作更改，会丢弃之后的步骤。", "點一下某個步驟即可返回該步驟。返回後再作更改，會捨棄之後的步驟。"),
"History.Compare": ("Show Original", "オリジナルを表示", "원본 보기", "显示原图", "顯示原圖"),
"History.Canvas": ("Canvas", "カンバス", "캔버스", "画布", "畫布"),
"History.AddLayer": ("Add Layer", "レイヤーを追加", "레이어 추가", "添加图层", "加入圖層"),
"History.DeleteLayer": ("Delete Layer", "レイヤーを削除", "레이어 삭제", "删除图层", "刪除圖層"),
"History.Reorder": ("Reorder Layers", "レイヤーを並べ替え", "레이어 순서 변경", "重新排列图层", "重新排列圖層"),
"History.Guides": ("Guides", "ガイド", "가이드", "参考线", "參考線"),
"History.Swatches": ("Swatches", "スウォッチ", "견본", "色板", "色票"),
"History.Groups": ("Groups", "グループ", "그룹", "组", "群組"),
"History.EditLayers": ("Edit Layers", "レイヤーを編集", "레이어 편집", "编辑图层", "編輯圖層"),
"History.EditPixels": ("Edit Layer", "レイヤーを編集", "레이어 편집", "编辑图层", "編輯圖層"),
"History.Opacity": ("Opacity", "不透明度", "불투명도", "不透明度", "不透明度"),
"History.BlendMode": ("Blend Mode", "描画モード", "혼합 모드", "混合模式", "混合模式"),
"History.Move": ("Move", "移動", "이동", "移动", "移動"),
"History.Text": ("Text", "テキスト", "텍스트", "文本", "文字"),
"History.Shape": ("Shape", "シェイプ", "모양", "形状", "形狀"),
"History.Filters": ("Filters", "フィルタ", "필터", "滤镜", "濾鏡"),
"History.Rename": ("Rename", "名前を変更", "이름 변경", "重新命名", "重新命名"),
"History.Visibility": ("Show or Hide", "表示/非表示", "보기/가리기", "显示或隐藏", "顯示或隱藏"),
"Intent.DefaultName": ("Image", "画像", "이미지", "图像", "影像"),
"Intent.Error.NoSize": ("Give a width, a height or both.", "幅か高さ、または両方を指定してください。", "너비나 높이 또는 둘 다 지정하십시오.", "请指定宽度、高度或两者。", "請指定寬度、高度或兩者。"),
"Intent.Format.Type": ("Format", "フォーマット", "포맷", "格式", "格式"),
"Intent.Parameter.Image": ("Image", "画像", "이미지", "图像", "影像"),
"Intent.Parameter.Width": ("Width", "幅", "너비", "宽度", "寬度"),
"Intent.Parameter.Height": ("Height", "高さ", "높이", "高度", "高度"),
"Intent.Parameter.KeepProportions": ("Keep Proportions", "縦横比を保持", "비율 유지", "保持比例", "保持比例"),
"Intent.Parameter.Format": ("Format", "フォーマット", "포맷", "格式", "格式"),
"Intent.Parameter.Quality": ("Quality", "画質", "품질", "质量", "品質"),
"Intent.Resize.Title": ("Resize Image", "画像のサイズを変更", "이미지 크기 조절", "调整图像大小", "調整影像大小"),
"Intent.Resize.Description": ("Scales an image to a new width or height, or both.", "画像を新しい幅や高さ、またはその両方に拡大・縮小します。", "이미지를 새 너비나 높이 또는 둘 다로 조절합니다.", "将图像缩放到新的宽度、高度或两者。", "將影像縮放到新的寬度、高度或兩者。"),
"Intent.Resize.Summary ${image} ${width} ${height}": ("Resize ${image} to ${width} × ${height}", "${image}を${width} × ${height}にサイズ変更", "${image}의 크기를 ${width} × ${height}(으)로 조절", "将${image}调整为${width} × ${height}", "將${image}調整為${width} × ${height}"),
"Intent.Convert.Title": ("Convert Image", "画像を変換", "이미지 변환", "转换图像", "轉換影像"),
"Intent.Convert.Description": ("Writes an image, or a flattened Photoshop document, in another format.", "画像や統合したPhotoshop書類を別のフォーマットで書き出します。", "이미지나 병합된 Photoshop 문서를 다른 포맷으로 저장합니다.", "以另一种格式写出图像或拼合的 Photoshop 文稿。", "以另一種格式寫出影像或合併的 Photoshop 文件。"),
"Intent.Convert.Summary ${image} ${format}": ("Convert ${image} to ${format}", "${image}を${format}に変換", "${image}을(를) ${format}(으)로 변환", "将${image}转换为${format}", "將${image}轉換為${format}"),
"Intent.RemoveBackground.Title": ("Remove Background", "背景を削除", "배경 제거", "移除背景", "移除背景"),
"Intent.RemoveBackground.Description": ("Keeps the people, animals and objects in an image and makes the rest transparent.", "画像内の人物、動物、物体を残し、それ以外を透明にします。", "이미지의 사람, 동물, 사물을 남기고 나머지를 투명하게 만듭니다.", "保留图像中的人物、动物和物体，其余部分变为透明。", "保留影像中的人物、動物和物體，其餘部分變為透明。"),
"Intent.RemoveBackground.Summary ${image}": ("Remove the background from ${image}", "${image}の背景を削除", "${image}의 배경 제거", "移除${image}的背景", "移除${image}的背景"),
"Edit.Copy": ("Copy", "コピー", "복사", "拷贝", "拷貝"),
"Edit.Cut": ("Cut", "カット", "잘라내기", "剪切", "剪下"),
"Edit.Paste": ("Paste as Layer", "レイヤーとしてペースト", "레이어로 붙여넣기", "粘贴为图层", "貼上為圖層"),
"ExportPreset.Menu": ("Export with Presets…", "プリセットで書き出す…", "프리셋으로 내보내기…", "使用预设导出…", "使用預設輸出…"),
"ExportPreset.Title": ("Batch Export", "一括書き出し", "일괄 내보내기", "批量导出", "批次輸出"),
"ExportPreset.Export": ("Export", "書き出す", "내보내기", "导出", "輸出"),
"ExportPreset.Share %lld": ("Share %lld Files", "%lld個のファイルを共有", "파일 %lld개 공유", "共享 %lld 个文件", "分享 %lld 個檔案"),
"ExportPreset.Footer": ("Choose one or more presets. Each makes its own file, named after the picture and the preset.", "1つ以上のプリセットを選択します。プリセットごとに、ピクチャとプリセットの名前が付いたファイルが作成されます。", "하나 이상의 프리셋을 선택하십시오. 프리셋마다 그림과 프리셋 이름이 붙은 파일이 만들어집니다.", "选择一个或多个预设。每个预设会生成一个以图片和预设命名的文件。", "選擇一個或多個預設。每個預設會產生一個以圖片和預設命名的檔案。"),
"ExportPreset.New": ("New Preset", "新規プリセット", "새로운 프리셋", "新建预设", "新增預設"),
"ExportPreset.Delete": ("Delete", "削除", "삭제", "删除", "刪除"),
"ExportPreset.Name": ("Name", "名前", "이름", "名称", "名稱"),
"ExportPreset.Format": ("Format", "フォーマット", "포맷", "格式", "格式"),
"ExportPreset.Quality": ("Quality", "画質", "품질", "质量", "品質"),
"ExportPreset.MaxWidth": ("Largest Width", "最大の幅", "최대 너비", "最大宽度", "最大寬度"),
"ExportPreset.MaxHeight": ("Largest Height", "最大の高さ", "최대 높이", "最大高度", "最大高度"),
"ExportPreset.Any": ("Any", "指定なし", "제한 없음", "不限", "不限"),
"ExportPreset.SizeFooter": ("The picture is shrunk to fit within these, keeping its proportions. It is never enlarged.", "縦横比を保ったまま、この範囲に収まるように縮小されます。拡大はされません。", "비율을 유지하며 이 크기 안에 맞도록 축소됩니다. 확대되지는 않습니다.", "图片会按比例缩小以适合这些尺寸，但不会放大。", "圖片會按比例縮小以符合這些尺寸，但不會放大。"),
"ExportPreset.Width %lld": ("%lld px wide", "幅%lld px", "너비 %lld px", "宽 %lld 像素", "寬 %lld 像素"),
"ExportPreset.Height %lld": ("%lld px tall", "高さ%lld px", "높이 %lld px", "高 %lld 像素", "高 %lld 像素"),
"ExportPreset.FullSize": ("Full size", "フルサイズ", "전체 크기", "全尺寸", "全尺寸"),
"ExportPreset.Web": ("Web", "Web", "웹", "网页", "網頁"),
"ExportPreset.Thumbnail": ("Thumbnail", "サムネール", "썸네일", "缩略图", "縮圖"),
"ExportPreset.Social": ("Social Post", "SNS投稿", "소셜 게시물", "社交帖子", "社群貼文"),
"ExportPreset.AppStore": ("App Store Screenshot", "App Storeスクリーンショット", "App Store 스크린샷", "App Store 截屏", "App Store 截圖"),
"ExportPreset.FullPNG": ("Full Size PNG", "フルサイズPNG", "전체 크기 PNG", "全尺寸 PNG", "全尺寸 PNG"),
"Options.Snap": ("Snap to Guides", "ガイドにスナップ", "가이드에 스냅", "对齐参考线", "對齊參考線"),
"Symmetry.Title": ("Symmetry", "対称", "대칭", "对称", "對稱"),
"Symmetry.Off": ("Off", "オフ", "끔", "关", "關閉"),
"Symmetry.Vertical": ("Left and Right", "左右", "좌우", "左右", "左右"),
"Symmetry.Horizontal": ("Top and Bottom", "上下", "상하", "上下", "上下"),
"Symmetry.Both": ("Four Ways", "上下左右", "상하좌우", "四向", "四向"),
"Ruler.Title": ("Ruler", "定規", "자", "直尺", "直尺"),
"Brush.Tip": ("Tip", "ブラシ先端", "브러시 팁", "笔尖", "筆尖"),
"Brush.Tip.Round": ("Round", "円形", "원형", "圆形", "圓形"),
"Brush.Tip.Pencil": ("Pencil", "鉛筆", "연필", "铅笔", "鉛筆"),
"Brush.Tip.Calligraphy": ("Calligraphy", "カリグラフィ", "캘리그라피", "书法", "書法"),
"Brush.Tip.Airbrush": ("Airbrush", "エアブラシ", "에어브러시", "喷枪", "噴槍"),
"Brush.Tip.Chalk": ("Chalk", "チョーク", "분필", "粉笔", "粉筆"),
"Brush.Tip.Marker": ("Marker", "マーカー", "마커", "马克笔", "麥克筆"),
"Brush.Tip.Charcoal": ("Charcoal", "木炭", "목탄", "炭笔", "炭筆"),
"Brush.Preset.Charcoal": ("Willow Charcoal", "木炭", "버드나무 목탄", "柳木炭笔", "柳木炭筆"),
"Brush.Tip.Crayon": ("Crayon", "クレヨン", "크레용", "蜡笔", "蠟筆"),
"Brush.Preset.Crayon": ("Wax Crayon", "クレヨン", "크레용", "蜡笔", "蠟筆"),
"Brush.Tip.Stipple": ("Stipple", "点描", "점묘", "点画", "點畫"),
"Brush.Preset.Stipple": ("Stippling Pen", "点描ペン", "점묘 펜", "点画笔", "點畫筆"),
"Brush.Tip.Pixel": ("Pixel", "ピクセル", "픽셀", "像素", "像素"),
"Brush.Preset.Pixel": ("Pixel Pencil", "ピクセルペン", "픽셀 연필", "像素铅笔", "像素鉛筆"),
"Brush.Tip.Bristle": ("Bristle", "毛筆", "강모", "鬃毛", "鬃毛"),
"Brush.Preset.Bristle": ("Bristle Brush", "毛のブラシ", "강모 브러시", "鬃毛刷", "鬃毛刷"),
"Brush.Tip.DryBrush": ("Dry Brush", "ドライブラシ", "드라이 브러시", "干笔", "乾筆"),
"Brush.Preset.DryBrush": ("Dry Brush", "ドライブラシ", "드라이 브러시", "干笔", "乾筆"),
"Brush.Tip.Flat": ("Flat", "平筆", "평붓", "平头笔", "平頭筆"),
"Brush.Preset.Flat": ("Flat Brush", "平筆", "평붓", "平头笔", "平頭筆"),
"Brush.Tip.Spatter": ("Spatter", "スパッタ", "스패터", "飞溅", "飛濺"),
"Brush.Preset.Spatter": ("Spatter", "スパッタ", "스패터", "飞溅", "飛濺"),
"Brush.Preset.Marker": ("Felt Marker", "フェルトマーカー", "펠트 마커", "毡头马克笔", "氈頭麥克筆"),
"Brush.Dynamics": ("Dynamics", "ダイナミクス", "다이내믹스", "动态", "動態"),
"Options.Taper": ("Taper", "入り抜き", "끝 가늘게", "笔锋", "筆鋒"),
"Options.FollowsStroke": ("Turn with Stroke", "ストロークに沿って回転", "획을 따라 회전", "随笔画旋转", "隨筆畫旋轉"),
"Options.Scatter": ("Scatter", "散布", "흩뿌리기", "散布", "散佈"),
"Options.SizeJitter": ("Size Jitter", "サイズのゆらぎ", "크기 변화", "大小抖动", "大小抖動"),
"Options.ColorJitter": ("Color Jitter", "色のゆらぎ", "색상 변화", "颜色抖动", "顏色抖動"),
"Options.SpeedThinning": ("Thin When Fast", "速さで細く", "빠르면 가늘게", "快速时变细", "快速時變細"),
"Tool.Brush": ("Brush", "ブラシ", "브러시", "画笔", "筆刷"),
"Tool.Transform": ("Transform", "変形", "변형", "变换", "變形"),
"Transform.Distort": ("Distort", "自由な形に", "왜곡", "扭曲", "扭曲"),
"Transform.Warp": ("Warp", "ワープ", "뒤틀기", "变形", "彎曲"),
"Transform.Reset": ("Reset", "リセット", "재설정", "复位", "重置"),
"Transform.Apply": ("Apply Transform", "変形を適用", "변형 적용", "应用变换", "套用變形"),
"Tool.Crop": ("Crop", "切り取り", "자르기", "裁剪", "裁切"),
"Tool.Eraser": ("Eraser", "消しゴム", "지우개", "橡皮擦", "橡皮擦"),
"Tool.Eyedropper": ("Eyedropper", "スポイト", "스포이드", "吸管", "滴管"),
"Tool.Fill": ("Paint Bucket", "塗りつぶし", "페인트 통", "油漆桶", "油漆桶"),
"Tool.Gradient": ("Gradient", "グラデーション", "그라디언트", "渐变", "漸層"),
"Tool.Move": ("Move", "移動", "이동", "移动", "移動"),
"Tool.Select": ("Select", "選択", "선택", "选择", "選取"),
"Tool.Shape": ("Shape", "図形", "도형", "形状", "形狀"),
"Tool.Text": ("Text", "テキスト", "텍스트", "文本", "文字"),
"Toolbar.Inspector": ("Show or Hide Inspector", "インスペクタを表示/非表示", "속성 보기/가리기", "显示或隐藏检查器", "顯示或隱藏檢閱器"),
"Toolbar.More": ("More", "その他", "더 보기", "更多", "更多"),
"Toolbar.Redo": ("Redo", "やり直す", "실행 복귀", "重做", "重做"),
"Toolbar.Share": ("Share", "共有", "공유", "共享", "分享"),
"Toolbar.Undo": ("Undo", "取り消す", "실행 취소", "撤销", "還原"),
}

LANGS = ["en", "ja", "ko", "zh-Hans", "zh-Hant"]

def catalog(entries):
    strings = {}
    for key in sorted(entries):
        strings[key] = {"extractionState": "manual", "localizations": {
            lang: {"stringUnit": {"state": "translated", "value": value}}
            for lang, value in zip(LANGS, entries[key])}}
    return {"sourceLanguage": "en", "strings": strings, "version": "1.0"}

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
with open(os.path.join(root, "Shared/Support/Localizable.xcstrings"), "w") as f:
    json.dump(catalog(S), f, ensure_ascii=False, indent=2)

INFO = {
"CFBundleDisplayName": ("Easel", "Easel", "Easel", "Easel", "Easel"),
"NSPhotoLibraryUsageDescription": ("Easel opens photos from your library and saves your edits back to them.", "Easelはライブラリの写真を開き、編集内容をその写真に保存します。", "Easel은 보관함의 사진을 열고 편집 내용을 해당 사진에 다시 저장합니다.", "Easel 会打开图库中的照片，并将你的编辑存储回这些照片。", "Easel 會打開圖庫中的照片，並將你的編輯儲存回這些照片。"),
"NSPhotoLibraryAddUsageDescription": ("Easel saves the images you export to your library.", "Easelは書き出した画像をライブラリに保存します。", "Easel은 내보낸 이미지를 보관함에 저장합니다.", "Easel 会将你导出的图像存储到图库。", "Easel 會將你輸出的影像儲存到圖庫。"),
}
with open(os.path.join(root, "Easel/Support/InfoPlist.xcstrings"), "w") as f:
    json.dump(catalog(INFO), f, ensure_ascii=False, indent=2)
# Siri phrases: each language's ways of asking, which keep the app's name.
SHORTCUTS = {
"Remove the background with ${applicationName}": ("Remove the background with ${applicationName}", "${applicationName} で背景を削除", "${applicationName}로 배경 제거", "用 ${applicationName} 移除背景", "用 ${applicationName} 移除背景"),
"Cut out a subject with ${applicationName}": ("Cut out a subject with ${applicationName}", "${applicationName} で被写体を切り抜く", "${applicationName}로 피사체 오려내기", "用 ${applicationName} 抠出主体", "用 ${applicationName} 去背主體"),
"Resize an image with ${applicationName}": ("Resize an image with ${applicationName}", "${applicationName} で画像のサイズを変更", "${applicationName}로 이미지 크기 조절", "用 ${applicationName} 调整图像大小", "用 ${applicationName} 調整影像大小"),
"Convert an image with ${applicationName}": ("Convert an image with ${applicationName}", "${applicationName} で画像を変換", "${applicationName}로 이미지 변환", "用 ${applicationName} 转换图像", "用 ${applicationName} 轉換影像"),
}
phrases = {}
for key in sorted(SHORTCUTS):
    phrases[key] = {"extractionState": "manual", "localizations": {
        lang: {"stringSet": {"state": "translated", "values": [value]}}
        for lang, value in zip(LANGS, SHORTCUTS[key])}}
with open(os.path.join(root, "Easel/Support/AppShortcuts.xcstrings"), "w") as f:
    json.dump({"sourceLanguage": "en", "strings": phrases, "version": "1.0"}, f, ensure_ascii=False, indent=2)
print(len(S), "strings")
