# Generates Shared/Support/Localizable.xcstrings and Easel/Support/InfoPlist.xcstrings.
# Each entry: key -> (en, ja, ko, zh-Hans, zh-Hant)
import json, os

S = {
"Adjust.Brightness": ("Brightness", "明るさ", "밝기", "亮度", "亮度"),
"Adjust.Contrast": ("Contrast", "コントラスト", "대비", "对比度", "對比度"),
"Adjust.Exposure": ("Exposure", "露出", "노출", "曝光", "曝光"),
"Adjust.Highlights": ("Highlights", "ハイライト", "하이라이트", "高光", "亮部"),
"Adjust.Hue": ("Hue", "色相", "색조", "色相", "色相"),
"Adjust.Reset": ("Reset Adjustments", "調整をリセット", "조절 재설정", "重置调整", "重置調整"),
"Adjust.Saturation": ("Saturation", "彩度", "채도", "饱和度", "飽和度"),
"Adjust.Shadows": ("Shadows", "シャドウ", "그림자", "阴影", "陰影"),
"Adjust.Sharpness": ("Sharpness", "シャープネス", "선명도", "锐度", "銳利度"),
"Adjust.Temperature": ("Warmth", "暖かみ", "따뜻함", "色温", "色溫"),
"Adjust.Tint": ("Tint", "色合い", "색조 보정", "色调", "色調"),
"Adjust.Vibrance": ("Vibrance", "自然な彩度", "생동감", "鲜明度", "鮮豔度"),
"Adjust.Vignette": ("Vignette", "ビネット", "비네트", "暗角", "暈影"),
"Alert.Error.Title": ("Something Went Wrong", "問題が発生しました", "문제가 발생했습니다", "出现问题", "發生問題"),
"BlendMode.Add": ("Add", "加算", "더하기", "相加", "相加"),
"BlendMode.Color": ("Color", "カラー", "색상", "颜色", "顏色"),
"BlendMode.ColorBurn": ("Color Burn", "焼き込みカラー", "색상 번", "颜色加深", "加深顏色"),
"BlendMode.ColorDodge": ("Color Dodge", "覆い焼きカラー", "색상 닷지", "颜色减淡", "加亮顏色"),
"BlendMode.Darken": ("Darken", "比較（暗）", "어둡게", "变暗", "變暗"),
"BlendMode.Difference": ("Difference", "差の絶対値", "차이", "差值", "差異化"),
"BlendMode.Exclusion": ("Exclusion", "除外", "제외", "排除", "排除"),
"BlendMode.HardLight": ("Hard Light", "ハードライト", "하드 라이트", "强光", "實光"),
"BlendMode.Hue": ("Hue", "色相", "색조", "色相", "色相"),
"BlendMode.Lighten": ("Lighten", "比較（明）", "밝게", "变亮", "變亮"),
"BlendMode.LinearBurn": ("Linear Burn", "焼き込み（リニア）", "선형 번", "线性加深", "線性加深"),
"BlendMode.Luminosity": ("Luminosity", "輝度", "광도", "明度", "明度"),
"BlendMode.Multiply": ("Multiply", "乗算", "곱하기", "正片叠底", "色彩增值"),
"BlendMode.Normal": ("Normal", "通常", "표준", "正常", "正常"),
"BlendMode.Overlay": ("Overlay", "オーバーレイ", "오버레이", "叠加", "覆蓋"),
"BlendMode.Saturation": ("Saturation", "彩度", "채도", "饱和度", "飽和度"),
"BlendMode.Screen": ("Screen", "スクリーン", "스크린", "滤色", "濾色"),
"BlendMode.SoftLight": ("Soft Light", "ソフトライト", "소프트 라이트", "柔光", "柔光"),
"Canvas.ActualSize": ("Actual Pixels", "実際のピクセル", "실제 픽셀", "实际像素", "實際像素"),
"Canvas.FitToScreen": ("Fit to Screen", "画面に合わせる", "화면에 맞추기", "适合屏幕", "符合螢幕"),
"Canvas.FlipHorizontal": ("Flip Horizontally", "左右に反転", "수평으로 뒤집기", "水平翻转", "水平翻轉"),
"Canvas.FlipVertical": ("Flip Vertically", "上下に反転", "수직으로 뒤집기", "垂直翻转", "垂直翻轉"),
"Canvas.ImageSize": ("Canvas Size…", "カンバスサイズ…", "캔버스 크기…", "画布大小…", "畫布大小⋯"),
"Canvas.RotateLeft": ("Rotate Left", "左に回転", "왼쪽으로 회전", "向左旋转", "向左旋轉"),
"Canvas.RotateRight": ("Rotate Right", "右に回転", "오른쪽으로 회전", "向右旋转", "向右旋轉"),
"CanvasSize.Picture": ("Picture", "画像", "사진", "图片", "圖片"),
"CanvasSize.Mode.Anchor": ("Keep Size", "サイズを維持", "크기 유지", "保持大小", "維持大小"),
"CanvasSize.Mode.Anchor.Footer": ("The picture stays the same size. The canvas grows around it or crops it, keeping the picture at the anchor.", "画像のサイズは変わりません。カンバスが画像の周りに広がるか切り取られ、画像は基準点の位置に置かれます。", "사진 크기는 그대로 유지됩니다. 캔버스가 사진 주변으로 넓어지거나 잘리며, 사진은 기준점에 놓입니다.", "图片大小保持不变。画布会在图片周围扩展或裁剪，图片保持在锚点位置。", "圖片大小維持不變。畫布會在圖片周圍擴展或裁切，圖片維持在錨點位置。"),
"CanvasSize.Mode.Proportional": ("Scale Proportionally", "縦横比を保って拡大・縮小", "비율에 맞춰 크기 조절", "等比缩放", "等比例縮放"),
"CanvasSize.Mode.Proportional.Footer": ("The picture scales evenly to fit inside the new canvas without distortion. Any room left over is placed using the anchor.", "画像は歪まないように縦横比を保ったまま、新しいカンバスに収まるよう拡大・縮小されます。余った部分は基準点に合わせて配置されます。", "사진이 왜곡 없이 새로운 캔버스 안에 맞도록 비율에 맞춰 크기가 조절됩니다. 남는 공간은 기준점에 따라 배치됩니다.", "图片会等比缩放以适合新画布而不变形。剩余空间根据锚点排列。", "圖片會等比例縮放以符合新畫布而不變形。剩餘空間會依錨點排列。"),
"CanvasSize.Mode.Stretch": ("Stretch to Fill", "引き伸ばして埋める", "늘려서 채우기", "拉伸以填充", "延展以填滿"),
"CanvasSize.Mode.Stretch.Footer": ("The picture is stretched to fill the new canvas exactly, which can change its proportions.", "画像は新しいカンバスにぴったり合うように引き伸ばされます。縦横比が変わる場合があります。", "사진이 새로운 캔버스를 정확히 채우도록 늘어나며, 비율이 바뀔 수 있습니다.", "图片会被拉伸以完全填满新画布，这可能会改变其比例。", "圖片會被延展以完全填滿新畫布，這可能會改變其比例。"),
"Common.Cancel": ("Cancel", "キャンセル", "취소", "取消", "取消"),
"Common.OK": ("OK", "OK", "확인", "好", "好"),
"Crop.Aspect.FourThree": ("4:3", "4:3", "4:3", "4:3", "4:3"),
"Crop.Aspect.Free": ("Freeform", "自由形式", "자유 형식", "自由格式", "自由形式"),
"Crop.Aspect.Original": ("Original", "オリジナル", "원본", "原始", "原始"),
"Crop.Aspect.SixteenNine": ("16:9", "16:9", "16:9", "16:9", "16:9"),
"Crop.Aspect.Square": ("Square", "正方形", "정사각형", "正方形", "正方形"),
"Crop.Aspect.ThreeTwo": ("3:2", "3:2", "3:2", "3:2", "3:2"),
"Error.DocumentDamaged": ("This image could not be opened because part of it is missing or damaged.", "この画像は、一部が見つからないか破損しているため開けませんでした。", "이미지의 일부가 없거나 손상되어 열 수 없습니다.", "无法打开此图像，因为其中部分内容缺失或已损坏。", "無法打開此影像，因為其中部分內容遺失或已損毀。"),
"Error.DocumentTooNew": ("This image was saved by a newer version of Easel. Update Easel to open it.", "この画像は新しいバージョンのEaselで保存されています。開くにはEaselをアップデートしてください。", "이 이미지는 최신 버전의 Easel에서 저장되었습니다. 열려면 Easel을 업데이트하십시오.", "此图像由更新版本的 Easel 存储。请更新 Easel 以打开它。", "此影像由較新版本的 Easel 儲存。請更新 Easel 以打開它。"),
"Error.ImageUnreadable": ("The picture could not be read.", "画像を読み込めませんでした。", "사진을 읽을 수 없습니다.", "无法读取图片。", "無法讀取圖片。"),
"Error.ImageUnwritable": ("The picture could not be saved.", "画像を保存できませんでした。", "사진을 저장할 수 없습니다.", "无法存储图片。", "無法儲存圖片。"),
"Error.ImportFailed": ("Some pictures could not be added.", "一部の画像を追加できませんでした。", "일부 사진을 추가할 수 없습니다.", "部分图片无法添加。", "部分圖片無法加入。"),
"Error.LayerHidden": ("The layer is hidden. Show it to paint on it.", "レイヤーが非表示です。ペイントするには表示してください。", "레이어가 가려져 있습니다. 칠하려면 레이어를 표시하십시오.", "图层已隐藏。请显示图层以在其上绘画。", "圖層已隱藏。請顯示圖層以在上面繪圖。"),
"Error.LayerLocked": ("The layer is locked. Unlock it in Layers to change it.", "レイヤーがロックされています。変更するには「レイヤー」でロックを解除してください。", "레이어가 잠겨 있습니다. 변경하려면 레이어에서 잠금을 해제하십시오.", "图层已锁定。请在“图层”中解锁以进行更改。", "圖層已鎖定。請在「圖層」中解鎖以進行更改。"),
"Error.NoLayer": ("Choose a layer first.", "先にレイヤーを選択してください。", "먼저 레이어를 선택하십시오.", "请先选择一个图层。", "請先選擇一個圖層。"),
"Error.NothingToPaste": ("There is no picture on the clipboard.", "クリップボードに画像がありません。", "클립보드에 사진이 없습니다.", "剪贴板上没有图片。", "剪貼板上沒有圖片。"),
"Error.PhotoUnavailable": ("The photo could not be opened. It may have been deleted or may still be downloading.", "写真を開けませんでした。削除されたか、まだダウンロード中の可能性があります。", "사진을 열 수 없습니다. 삭제되었거나 아직 다운로드 중일 수 있습니다.", "无法打开照片。它可能已被删除或仍在下载。", "無法打開照片。它可能已被刪除或仍在下載。"),
"Error.PhotosAccessDenied": ("Easel needs access to your photo library. You can allow it in Settings.", "Easelには写真ライブラリへのアクセスが必要です。「設定」で許可できます。", "Easel이 사진 보관함에 접근해야 합니다. 설정에서 허용할 수 있습니다.", "Easel 需要访问你的照片图库。你可以在“设置”中允许访问。", "Easel 需要取用你的照片圖庫。你可以在「設定」中允許取用。"),
"Export.DefaultName": ("Image", "画像", "이미지", "图像", "影像"),
"Export.Easel": ("Easel Image (Layers)", "Easel画像（レイヤー付き）", "Easel 이미지(레이어 포함)", "Easel 图像（含图层）", "Easel 影像（含圖層）"),
"Export.HEIC": ("HEIC", "HEIC", "HEIC", "HEIC", "HEIC"),
"Export.JPEG": ("JPEG", "JPEG", "JPEG", "JPEG", "JPEG"),
"Export.PNG": ("PNG", "PNG", "PNG", "PNG", "PNG"),
"Export.SaveToPhotos": ("Save to Photos", "写真に保存", "사진에 저장", "存储到照片", "儲存到照片"),
"Export.ShareAs": ("Share As", "共有する形式", "공유 형식", "共享格式", "分享格式"),
"Filter.Bloom": ("Bloom", "ブルーム", "블룸", "柔光晕", "光暈"),
"Filter.Chrome": ("Chrome", "クローム", "크롬", "铬黄", "鉻黃"),
"Filter.Comic": ("Comic", "コミック", "만화", "漫画", "漫畫"),
"Filter.Crystallize": ("Crystallize", "結晶化", "결정화", "晶格化", "結晶化"),
"Filter.Fade": ("Fade", "フェード", "바랜 효과", "褪色", "褪色"),
"Filter.Instant": ("Instant", "インスタント", "인스턴트", "拍立得", "即可拍"),
"Filter.Invert": ("Invert", "階調の反転", "반전", "反相", "負片"),
"Filter.Mono": ("Mono", "モノ", "모노", "单色", "單色"),
"Filter.Noir": ("Noir", "ノワール", "누아르", "黑白", "黑白"),
"Filter.Noise": ("Grain", "粒子", "그레인", "颗粒", "顆粒"),
"Filter.None": ("Original", "オリジナル", "원본", "原片", "原始"),
"Filter.Posterize": ("Posterize", "ポスタリゼーション", "포스터화", "色调分离", "色調分離"),
"Filter.Process": ("Process", "プロセス", "프로세스", "冲印", "沖印"),
"Filter.Sepia": ("Sepia", "セピア", "세피아", "棕褐色", "懷舊"),
"Filter.Sharpen": ("Sharpen", "シャープ", "선명하게", "锐化", "銳利化"),
"Filter.Tonal": ("Tonal", "トーン", "색조 흑백", "色调", "色調"),
"Filter.Transfer": ("Transfer", "トランスファー", "트랜스퍼", "岁月", "歲月"),
"Filters.Intensity": ("Intensity", "強さ", "강도", "强度", "強度"),
"Filters.Section.Color": ("Color", "カラー", "색상", "颜色", "顏色"),
"Filters.Section.Effects": ("Effects", "エフェクト", "효과", "效果", "效果"),
"Filters.Section.Looks": ("Looks", "ルック", "룩", "风格", "風格"),
"ImageSize.Anchor": ("Anchor", "基準点", "기준점", "锚点", "錨點"),
"ImageSize.Height": ("Height", "高さ", "높이", "高度", "高度"),
"ImageSize.KeepProportions": ("Keep Proportions", "縦横比を固定", "비율 유지", "保持比例", "維持比例"),
"ImageSize.Original %lld %lld": ("Currently %1$lld × %2$lld pixels", "現在 %1$lld × %2$lld ピクセル", "현재 %1$lld × %2$lld 픽셀", "当前为 %1$lld × %2$lld 像素", "目前為 %1$lld × %2$lld 像素"),
"ImageSize.Pixels": ("px", "px", "px", "像素", "像素"),
"ImageSize.Width": ("Width", "幅", "너비", "宽度", "寬度"),
"LayerFilter.BlackAndWhite": ("Black & White", "白黒", "흑백", "黑白", "黑白"),
"LayerFilter.Brightness": ("Brightness", "明るさ", "밝기", "亮度", "亮度"),
"LayerFilter.Contrast": ("Contrast", "コントラスト", "대비", "对比度", "對比度"),
"LayerFilter.GaussianBlur": ("Gaussian Blur", "ぼかし（ガウス）", "가우시안 흐림", "高斯模糊", "高斯模糊"),
"LayerFilter.Mosaic": ("Mosaic", "モザイク", "모자이크", "马赛克", "馬賽克"),
"LayerFilter.MotionBlur": ("Motion Blur", "ぼかし（移動）", "동작 흐림", "动感模糊", "動態模糊"),
"LayerFilter.Saturation": ("Saturation", "彩度", "채도", "饱和度", "飽和度"),
"LayerFilter.Sepia": ("Sepia", "セピア", "세피아", "棕褐色", "懷舊"),
"LayerFilter.ZoomBlur": ("Zoom Blur", "ぼかし（ズーム）", "확대/축소 흐림", "缩放模糊", "縮放模糊"),
"LayerFilters.Add": ("Add Filter", "フィルタを追加", "필터 추가", "添加滤镜", "加入濾鏡"),
"LayerFilters.Amount": ("Amount", "量", "양", "数量", "數量"),
"LayerFilters.Angle": ("Angle", "角度", "각도", "角度", "角度"),
"LayerFilters.ApplyAll": ("Apply Filters to Layer", "フィルタをレイヤーに適用", "레이어에 필터 적용", "将滤镜应用到图层", "將濾鏡套用至圖層"),
"LayerFilters.CenterX": ("Center (Horizontal)", "中心（水平）", "중심(수평)", "中心（水平）", "中心（水平）"),
"LayerFilters.CenterY": ("Center (Vertical)", "中心（垂直）", "중심(수직)", "中心（垂直）", "中心（垂直）"),
"LayerFilters.Empty": ("No Filters", "フィルタなし", "필터 없음", "没有滤镜", "沒有濾鏡"),
"LayerFilters.Empty.Detail": ("Filters change how this layer looks without changing its pixels, so they can be adjusted or removed at any time.", "フィルタはピクセルを変更せずにレイヤーの見た目を変えるので、いつでも調整したり取り除いたりできます。", "필터는 픽셀을 변경하지 않고 레이어의 모양을 바꾸므로 언제든지 조절하거나 제거할 수 있습니다.", "滤镜会更改此图层的外观而不更改其像素，因此可以随时调整或移除。", "濾鏡會更改此圖層的外觀而不更改其像素，因此可以隨時調整或移除。"),
"LayerFilters.Hide": ("Turn Off Filter", "フィルタをオフにする", "필터 끄기", "关闭滤镜", "關閉濾鏡"),
"LayerFilters.Show": ("Turn On Filter", "フィルタをオンにする", "필터 켜기", "打开滤镜", "開啟濾鏡"),
"LayerFilters.Footer": ("Filters run from top to bottom. Touch and hold a filter to drag it into a new place.", "フィルタは上から順に適用されます。フィルタを長押しすると、ドラッグして並べ替えられます。", "필터는 위에서 아래 순서로 적용됩니다. 필터를 길게 터치하여 드래그하면 순서를 변경할 수 있습니다.", "滤镜从上到下依次应用。按住滤镜即可拖移以重新排序。", "濾鏡由上至下依序套用。按住濾鏡即可拖移以重新排序。"),
"LayerFilters.Remove": ("Remove Filter", "フィルタを削除", "필터 제거", "移除滤镜", "移除濾鏡"),
"LayerFilters.RemoveAll": ("Remove All Filters", "すべてのフィルタを削除", "모든 필터 제거", "移除所有滤镜", "移除所有濾鏡"),
"Panel.Looks.Title": ("Looks", "ルック", "룩", "风格", "風格"),
"Mask.Title": ("Mask", "マスク", "마스크", "蒙版", "遮色片"),
"Mask.Add": ("Add Mask", "マスクを追加", "마스크 추가", "添加蒙版", "加入遮色片"),
"Mask.AddFromSelection": ("Add Mask from Selection", "選択範囲からマスクを追加", "선택 영역에서 마스크 추가", "从选区添加蒙版", "從選取範圍加入遮色片"),
"Mask.Edit": ("Paint on Mask", "マスクにペイント", "마스크에 칠하기", "在蒙版上绘画", "在遮色片上繪圖"),
"Mask.Enabled": ("Use Mask", "マスクを使用", "마스크 사용", "使用蒙版", "使用遮色片"),
"Mask.Actions": ("Mask Actions", "マスクの操作", "마스크 동작", "蒙版操作", "遮色片動作"),
"Mask.HideSelection": ("Hide Selection", "選択範囲を隠す", "선택 영역 가리기", "隐藏选区", "隱藏選取範圍"),
"Mask.RevealSelection": ("Reveal Selection", "選択範囲を表示", "선택 영역 표시", "显示选区", "顯示選取範圍"),
"Mask.Invert": ("Invert Mask", "マスクを反転", "마스크 반전", "反转蒙版", "反轉遮色片"),
"Mask.Apply": ("Apply Mask to Layer", "マスクをレイヤーに適用", "레이어에 마스크 적용", "将蒙版应用到图层", "將遮色片套用至圖層"),
"Mask.Delete": ("Delete Mask", "マスクを削除", "마스크 삭제", "删除蒙版", "刪除遮色片"),
"Mask.Footer": ("While painting on the mask, the brush hides the layer and the eraser reveals it again.", "マスクにペイントしている間は、ブラシでレイヤーを隠し、消しゴムで再び表示できます。", "마스크에 칠하는 동안 브러시는 레이어를 가리고 지우개는 다시 표시합니다.", "在蒙版上绘画时，画笔会隐藏图层，橡皮擦会重新显示图层。", "在遮色片上繪圖時，筆刷會隱藏圖層，橡皮擦會重新顯示圖層。"),
"Mask.Editing": ("Painting on Mask", "マスクにペイント中", "마스크에 칠하는 중", "正在蒙版上绘画", "正在遮色片上繪圖"),
"Error.MaskTool": ("Only the brush, eraser and gradient can paint on a mask.", "マスクにペイントできるのは、ブラシ、消しゴム、グラデーションだけです。", "마스크에는 브러시, 지우개, 그라디언트만 칠할 수 있습니다.", "只有画笔、橡皮擦和渐变可以在蒙版上绘画。", "只有筆刷、橡皮擦和漸層可以在遮色片上繪圖。"),
"Error.NoObjectFound": ("No people, animals or objects were found in the picture.", "画像内に人物、動物、物体が見つかりませんでした。", "사진에서 사람, 동물 또는 사물을 찾을 수 없습니다.", "未在图片中找到人物、动物或物体。", "未在圖片中找到人物、動物或物體。"),
"Error.NoObjectHere": ("There is no object there. Tap a person, animal or thing to select it.", "そこにはオブジェクトがありません。人物、動物、物体をタップして選択してください。", "그곳에는 개체가 없습니다. 사람, 동물 또는 사물을 탭하여 선택하십시오.", "那里没有对象。请轻点人物、动物或物体以选择。", "那裡沒有物件。請點一下人物、動物或物體以選取。"),
"Error.ObjectSelectionUnavailable": ("Object selection isn't available on this device.", "このデバイスではオブジェクト選択を使用できません。", "이 기기에서는 개체 선택을 사용할 수 없습니다.", "此设备不支持选择对象。", "此裝置不支援選取物件。"),
"Error.PSDUnsupported": ("This Photoshop document uses a colour mode or size Easel can't open.", "このPhotoshop書類は、Easelで開けないカラーモードまたはサイズを使用しています。", "이 Photoshop 문서는 Easel에서 열 수 없는 색상 모드 또는 크기를 사용합니다.", "此 Photoshop 文稿使用了 Easel 无法打开的颜色模式或尺寸。", "此 Photoshop 文件使用了 Easel 無法打開的色彩模式或尺寸。"),
"Launch.EditPhoto": ("Edit a Photo", "写真を編集", "사진 편집", "编辑照片", "編輯照片"),
"Launch.NewImage": ("New Image", "新規画像", "새로운 이미지", "新建图像", "新增影像"),
"Launch.Title": ("Easel", "Easel", "Easel", "Easel", "Easel"),
"Layer.CopyName %@": ("%@ Copy", "%@のコピー", "%@ 사본", "%@ 副本", "%@ 副本"),
"Layer.DefaultName.Background": ("Background", "背景", "배경", "背景", "背景"),
"Layer.DefaultName.Image": ("Image", "画像", "이미지", "图像", "影像"),
"Layer.DefaultName.Layer": ("Layer", "レイヤー", "레이어", "图层", "圖層"),
"Layer.DefaultName.Pasted": ("Pasted", "ペースト", "붙여넣음", "粘贴", "貼上"),
"Layer.DefaultName.PixelmatorPreview": ("Pixelmator Preview", "Pixelmatorのプレビュー", "Pixelmator 미리보기", "Pixelmator 预览", "Pixelmator 預覽"),
"Layer.DefaultName.Photo": ("Photo", "写真", "사진", "照片", "照片"),
"Layers.Add": ("Add Layer", "レイヤーを追加", "레이어 추가", "添加图层", "加入圖層"),
"Layers.BlendMode": ("Blend Mode", "描画モード", "혼합 모드", "混合模式", "混合模式"),
"Layers.Copy": ("Copy", "コピー", "복사", "拷贝", "拷貝"),
"Layers.Delete": ("Delete Layer", "レイヤーを削除", "레이어 삭제", "删除图层", "刪除圖層"),
"Layers.Duplicate": ("Duplicate", "複製", "복제", "复制", "複製"),
"Layers.Flatten": ("Flatten Image", "画像を統合", "이미지 병합", "拼合图像", "影像平面化"),
"Layers.Hide": ("Hide Layer", "レイヤーを非表示", "레이어 가리기", "隐藏图层", "隱藏圖層"),
"Layers.ImportFiles": ("From Files", "“ファイル”から", "파일에서", "从“文件”", "從「檔案」"),
"Layers.ImportPhotos": ("From Photos", "“写真”から", "사진에서", "从“照片”", "從「照片」"),
"Layers.Lock": ("Lock", "ロック", "잠금", "锁定", "鎖定"),
"Layers.Locked": ("Locked", "ロック中", "잠김", "已锁定", "已鎖定"),
"Layers.MergeDown": ("Merge Down", "下のレイヤーと結合", "아래 레이어와 병합", "向下合并", "向下合併"),
"Layers.More": ("More", "その他", "더 보기", "更多", "更多"),
"Layers.MoveDown": ("Move Down", "下へ移動", "아래로 이동", "下移", "下移"),
"Layers.MoveUp": ("Move Up", "上へ移動", "위로 이동", "上移", "上移"),
"Layers.NewLayer": ("New Layer", "新規レイヤー", "새로운 레이어", "新建图层", "新增圖層"),
"Layers.Opacity": ("Opacity", "不透明度", "불투명도", "不透明度", "不透明度"),
"Layers.Paste": ("Paste", "ペースト", "붙여넣기", "粘贴", "貼上"),
"Layers.Rasterize": ("Rasterize", "ラスタライズ", "래스터화", "栅格化", "點陣化"),
"Layers.Rename": ("Rename", "名称変更", "이름 변경", "重新命名", "重新命名"),
"Layers.Rename.Confirm": ("Rename", "名称変更", "이름 변경", "重新命名", "重新命名"),
"Layers.Rename.Placeholder": ("Layer Name", "レイヤー名", "레이어 이름", "图层名称", "圖層名稱"),
"Layers.Rename.Title": ("Rename Layer", "レイヤー名を変更", "레이어 이름 변경", "重新命名图层", "重新命名圖層"),
"Layers.Section.Appearance": ("Layer", "レイヤー", "레이어", "图层", "圖層"),
"Layers.Show": ("Show Layer", "レイヤーを表示", "레이어 표시", "显示图层", "顯示圖層"),
"Layers.Unlock": ("Unlock", "ロックを解除", "잠금 해제", "解锁", "解鎖"),
"Options.AspectRatio": ("Aspect Ratio", "縦横比", "화면 비율", "长宽比", "長寬比"),
"Options.BrushSettings": ("Brush Settings", "ブラシ設定", "브러시 설정", "画笔设置", "筆刷設定"),
"Options.Color": ("Color", "カラー", "색상", "颜色", "顏色"),
"Options.CropApply": ("Crop", "切り取る", "자르기", "裁剪", "裁切"),
"Options.CropReset": ("Reset Crop", "切り取りをリセット", "자르기 재설정", "重置裁剪", "重置裁切"),
"Options.EditText": ("Edit Text", "テキストを編集", "텍스트 편집", "编辑文本", "編輯文字"),
"Options.FitToCanvas": ("Fit to Canvas", "カンバスに合わせる", "캔버스에 맞추기", "适合画布", "符合畫布"),
"Options.FlipHorizontal": ("Flip Layer Horizontally", "レイヤーを左右に反転", "레이어를 수평으로 뒤집기", "水平翻转图层", "水平翻轉圖層"),
"Options.FlipVertical": ("Flip Layer Vertically", "レイヤーを上下に反転", "레이어를 수직으로 뒤집기", "垂直翻转图层", "垂直翻轉圖層"),
"Options.LineWidth": ("Line Width", "線の太さ", "선 두께", "线宽", "線條寬度"),
"Options.Opacity": ("Opacity", "不透明度", "불투명도", "不透明度", "不透明度"),
"Options.PencilPressure": ("Apple Pencil Pressure", "Apple Pencilの筆圧", "Apple Pencil 압력", "Apple Pencil 压力", "Apple Pencil 壓力"),
"Options.ResetTransform": ("Reset Size and Position", "サイズと位置をリセット", "크기 및 위치 재설정", "重置大小和位置", "重置大小與位置"),
"Options.RotateLayer": ("Rotate Layer", "レイヤーを回転", "레이어 회전", "旋转图层", "旋轉圖層"),
"Options.Rotation": ("Rotation", "回転", "회전", "旋转", "旋轉"),
"Options.Scale": ("Scale", "拡大・縮小", "크기", "缩放", "縮放"),
"Options.SelectionActions": ("Selection", "選択範囲", "선택 영역", "选区", "選取範圍"),
"Options.ShapeFilled": ("Fill Shape", "図形を塗りつぶす", "도형 채우기", "填充形状", "填滿形狀"),
"Options.Size": ("Size", "サイズ", "크기", "大小", "大小"),
"Options.Softness": ("Softness", "やわらかさ", "부드러움", "柔和度", "柔和度"),
"Options.TapToAddText": ("Tap to add text", "タップしてテキストを追加", "탭하여 텍스트 추가", "轻点以添加文本", "點一下以加入文字"),
"Options.Tolerance": ("Tolerance", "許容値", "허용치", "容差", "容許度"),
"Options.Transform": ("Size and Rotation", "サイズと回転", "크기 및 회전", "大小与旋转", "大小與旋轉"),
"Panel.Adjustments.Title": ("Adjust", "調整", "조절", "调整", "調整"),
"Panel.Filters.Title": ("Filters", "フィルタ", "필터", "滤镜", "濾鏡"),
"Panel.ImageSize.Title": ("Canvas Size", "カンバスサイズ", "캔버스 크기", "画布大小", "畫布大小"),
"Panel.Layers.Title": ("Layers", "レイヤー", "레이어", "图层", "圖層"),
"Panel.Text.Title": ("Text", "テキスト", "텍스트", "文本", "文字"),
"PhotoEditor.Discard.Confirm": ("Discard Changes", "変更内容を破棄", "변경 사항 폐기", "放弃更改", "放棄更改"),
"PhotoEditor.Discard.Title": ("Discard your changes to this photo?", "この写真への変更内容を破棄しますか?", "이 사진의 변경 사항을 폐기하겠습니까?", "要放弃对此照片的更改吗？", "要放棄對此照片的更改嗎？"),
"PhotoEditor.Revert": ("Revert to Original", "オリジナルに戻す", "원본으로 복귀", "复原到原始状态", "回復成原始狀態"),
"PhotoEditor.Save": ("Save", "保存", "저장", "存储", "儲存"),
"PhotoEditor.Title": ("Edit Photo", "写真を編集", "사진 편집", "编辑照片", "編輯照片"),
"Select.All": ("Select All", "すべてを選択", "모두 선택", "全选", "全選"),
"Select.Clear": ("Delete Selected Area", "選択範囲を削除", "선택 영역 삭제", "删除选区内容", "刪除選取範圍內容"),
"Select.CopyToLayer": ("Copy to New Layer", "新規レイヤーにコピー", "새로운 레이어로 복사", "拷贝到新图层", "拷貝到新圖層"),
"Select.CropToSelection": ("Crop to Selection", "選択範囲で切り取る", "선택 영역으로 자르기", "裁剪到选区", "裁切至選取範圍"),
"Select.CutToLayer": ("Cut to New Layer", "新規レイヤーにカット", "새로운 레이어로 오려두기", "剪切到新图层", "剪下至新圖層"),
"Select.Deselect": ("Deselect", "選択を解除", "선택 해제", "取消选择", "取消選取"),
"Select.Ellipse": ("Ellipse", "楕円形", "타원", "椭圆", "橢圓"),
"Select.Fill": ("Fill Selection", "選択範囲を塗りつぶす", "선택 영역 채우기", "填充选区", "填滿選取範圍"),
"Select.Invert": ("Invert Selection", "選択範囲を反転", "선택 영역 반전", "反选", "反轉選取範圍"),
"Select.Lasso": ("Freehand", "フリーハンド", "자유형", "手绘", "手繪"),
"Select.Magic": ("Magic Select", "自動選択", "자동 선택", "魔棒", "魔術棒"),
"Select.Magnetic": ("Magnetic Lasso", "マグネット選択", "자석 올가미", "磁性套索", "磁性套索"),
"Select.Object": ("Object Select", "オブジェクト選択", "개체 선택", "选择对象", "選取物件"),
"Select.Subject": ("Select Subject", "被写体を選択", "피사체 선택", "选择主体", "選取主體"),
"Select.Rectangle": ("Rectangle", "長方形", "직사각형", "矩形", "矩形"),
"Shape.Arrow": ("Arrow", "矢印", "화살표", "箭头", "箭頭"),
"Shape.Ellipse": ("Ellipse", "楕円形", "타원", "椭圆", "橢圓"),
"Shape.Line": ("Line", "線", "선", "线条", "線條"),
"Shape.Rectangle": ("Rectangle", "長方形", "직사각형", "矩形", "矩形"),
"Text.Outline": ("Outline", "輪郭", "외곽선", "轮廓", "外框"),
"Text.Outline.Show": ("Outline Text", "テキストに輪郭を付ける", "텍스트 외곽선", "为文本添加轮廓", "為文字加上外框"),
"Text.Outline.Width": ("Width", "太さ", "두께", "宽度", "寬度"),
"Text.Background": ("Background", "背景", "배경", "背景", "背景"),
"Text.Background.Show": ("Background Box", "背景ボックス", "배경 상자", "背景框", "背景框"),
"Text.Background.Padding": ("Padding", "余白", "여백", "边距", "邊距"),
"Text.Background.Corners": ("Rounded Corners", "角の丸み", "둥근 모서리", "圆角", "圓角"),
"Text.Alignment": ("Alignment", "揃え", "정렬", "对齐", "對齊"),
"Text.Alignment.Center": ("Center", "中央揃え", "가운데 정렬", "居中", "置中"),
"Text.Alignment.Leading": ("Left", "左揃え", "왼쪽 정렬", "左对齐", "靠左"),
"Text.Alignment.Trailing": ("Right", "右揃え", "오른쪽 정렬", "右对齐", "靠右"),
"Text.Bold": ("Bold", "太字", "볼드체", "粗体", "粗體"),
"Text.Color": ("Color", "カラー", "색상", "颜色", "顏色"),
"Text.Design": ("Font", "フォント", "서체", "字体", "字體"),
"Text.Design.Default": ("System", "システム", "시스템", "系统", "系統"),
"Text.Design.Monospaced": ("Monospaced", "等幅", "고정폭", "等宽", "等寬"),
"Text.Design.Rounded": ("Rounded", "丸ゴシック", "둥근", "圆体", "圓體"),
"Text.Design.Serif": ("Serif", "セリフ", "세리프", "衬线", "襯線"),
"Text.Italic": ("Italic", "斜体", "이탤릭체", "斜体", "斜體"),
"Text.NoTextLayer": ("No Text Layer", "テキストレイヤーがありません", "텍스트 레이어 없음", "没有文本图层", "沒有文字圖層"),
"Text.NoTextLayer.Detail": ("Pick the Text tool and tap the canvas to add text.", "テキストツールを選んでカンバスをタップすると、テキストを追加できます。", "텍스트 도구를 선택하고 캔버스를 탭하여 텍스트를 추가하십시오.", "选择文本工具并轻点画布以添加文本。", "選擇文字工具並點一下畫布以加入文字。"),
"Text.Placeholder": ("Text", "テキスト", "텍스트", "文本", "文字"),
"Text.Size": ("Size", "サイズ", "크기", "大小", "大小"),
"TitleMenu.ConvertToEasel": ("Keep Layers", "レイヤーを保持", "레이어 유지", "保留图层", "保留圖層"),
"TitleMenu.ConvertToEasel.Footer": ("Pictures are flattened when saved. Turn this file into an Easel image to keep its layers.", "画像ファイルは保存時に統合されます。レイヤーを保持するには、このファイルをEasel画像に変換してください。", "사진 파일은 저장할 때 병합됩니다. 레이어를 유지하려면 이 파일을 Easel 이미지로 변환하십시오.", "图片在存储时会被拼合。将此文件转换为 Easel 图像以保留其图层。", "圖片在儲存時會被平面化。將此檔案轉換為 Easel 影像以保留其圖層。"),
"Tool.Blur": ("Blur", "ぼかし", "흐림", "模糊", "模糊"),
"Tool.Heal": ("Heal", "修復", "복구", "修复", "修復"),
"Tool.Mosaic": ("Mosaic", "モザイク", "모자이크", "马赛克", "馬賽克"),
"Tool.Smudge": ("Smudge", "指先", "손가락", "涂抹", "指尖"),
"Options.Strength": ("Strength", "強さ", "강도", "强度", "強度"),
"Tool.Brush": ("Brush", "ブラシ", "브러시", "画笔", "筆刷"),
"Tool.Crop": ("Crop", "切り取り", "자르기", "裁剪", "裁切"),
"Tool.Eraser": ("Eraser", "消しゴム", "지우개", "橡皮擦", "橡皮擦"),
"Tool.Eyedropper": ("Eyedropper", "スポイト", "스포이드", "吸管", "滴管"),
"Tool.Fill": ("Paint Bucket", "塗りつぶし", "페인트 통", "油漆桶", "油漆桶"),
"Tool.Gradient": ("Gradient", "グラデーション", "그라디언트", "渐变", "漸層"),
"Tool.Move": ("Move", "移動", "이동", "移动", "移動"),
"Tool.Select": ("Select", "選択", "선택", "选择", "選取"),
"Tool.Shape": ("Shape", "図形", "도형", "形状", "形狀"),
"Tool.Text": ("Text", "テキスト", "텍스트", "文本", "文字"),
"Toolbar.Inspector": ("Show or Hide Inspector", "インスペクタを表示/非表示", "속성 보기/가리기", "显示或隐藏检查器", "顯示或隱藏檢閱器"),
"Toolbar.Redo": ("Redo", "やり直す", "실행 복귀", "重做", "重做"),
"Toolbar.Share": ("Share", "共有", "공유", "共享", "分享"),
"Toolbar.Undo": ("Undo", "取り消す", "실행 취소", "撤销", "還原"),
}

LANGS = ["en", "ja", "ko", "zh-Hans", "zh-Hant"]

def catalog(entries):
    strings = {}
    for key in sorted(entries):
        strings[key] = {"extractionState": "manual", "localizations": {
            lang: {"stringUnit": {"state": "translated", "value": value}}
            for lang, value in zip(LANGS, entries[key])}}
    return {"sourceLanguage": "en", "strings": strings, "version": "1.0"}

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
with open(os.path.join(root, "Shared/Support/Localizable.xcstrings"), "w") as f:
    json.dump(catalog(S), f, ensure_ascii=False, indent=2)

INFO = {
"CFBundleDisplayName": ("Easel", "Easel", "Easel", "Easel", "Easel"),
"NSPhotoLibraryUsageDescription": ("Easel opens photos from your library and saves your edits back to them.", "Easelはライブラリの写真を開き、編集内容をその写真に保存します。", "Easel은 보관함의 사진을 열고 편집 내용을 해당 사진에 다시 저장합니다.", "Easel 会打开图库中的照片，并将你的编辑存储回这些照片。", "Easel 會打開圖庫中的照片，並將你的編輯儲存回這些照片。"),
"NSPhotoLibraryAddUsageDescription": ("Easel saves the images you export to your library.", "Easelは書き出した画像をライブラリに保存します。", "Easel은 내보낸 이미지를 보관함에 저장합니다.", "Easel 会将你导出的图像存储到图库。", "Easel 會將你輸出的影像儲存到圖庫。"),
}
with open(os.path.join(root, "Easel/Support/InfoPlist.xcstrings"), "w") as f:
    json.dump(catalog(INFO), f, ensure_ascii=False, indent=2)
print(len(S), "strings")
